/*
*	Empyrean Medical Systems
*	08/2018
*	Project: Gryphon System Control Firmware
*	Module: System monitoring
*	Author: Carlton Chow
*	Description:
*/


#ifndef HVPS_MONITORING_H_
#define HVPS_MONITORING_H_

#include "system_monitoring.h"

#define LOW_KV_THRESH				5.0f

#define HVPS_MONITOR_MS				(SYSTEM_MONITOR_INTERVAL * SYS_MON_NUM_ROUNDS)

#define WARMUP_STABILITY_CHECK		(1 * (1000/HVPS_MONITOR_MS))
#define LAUNCHING_STABILITY_CHECK	(1 * (1000/HVPS_MONITOR_MS))
#define SETUP_STABILITY_CHECK		(1 * (1000/HVPS_MONITOR_MS))
#define TERM_STABILITY_CHECK		(1 * (1000/HVPS_MONITOR_MS))
#define WARMUP_RUNNING_CHECK		(3 * (1000/HVPS_MONITOR_MS))
#define WARMUP_TIMEOUT				(180 * (1000/HVPS_MONITOR_MS))
#define CONDITIONING_TIMEOUT		(360 * (1000/HVPS_MONITOR_MS))
#define SETUP_TIMEOUT				(150 * (1000/HVPS_MONITOR_MS))
#define LAUNCHING_TIMEOUT			(120 * (1000/HVPS_MONITOR_MS))			
#define DISCHARGE_TIMEOUT			(75 * (1000/HVPS_MONITOR_MS))
#define TERMINATION_TIMEOUT			(75 * (1000/HVPS_MONITOR_MS))

#define MA_UNSTABLE_TIME			(6 * (1000/HVPS_MONITOR_MS))
#define MA_UNWANTED_TIME			(1 * (1000/HVPS_MONITOR_MS))

#define HEATER_MIN_FEEDBACK			700

typedef enum hvpsExpected
{
	HVPS_EXPECTED_KV = 0,
	HVPS_EXPECTED_MA,
	HVPS_EXPECTED_GRID,
	HVPS_EXPECTED_FIL,
	HVPS_EXPECTED_FIL_OUT,
	HVPS_EXPECTED_CNT
} HvpsExpected;

typedef enum hvpsSp
{
	HVPS_SP_PWR = 0,
	HVPS_SP_KV,
	HVPS_SP_MA_LIM,
	HVPS_SP_GRID,
	HVPS_SP_FIL,
	HVPS_SP_CNT
} HvpsSp;

enum
{
	HVPS_SYS_STAT_TEST = 0,
	HVPS_SYS_STAT_HV_CTRL_EN,
	HVPS_SYS_STAT_GRID_CTRL_EN,
	HVPS_SYS_STAT_WARMING,
	HVPS_SYS_STAT_KV_RAMPING,
	HVPS_SYS_STAT_EMISSION_ON,
	HVPS_SYS_STAT_UNLOCKED_CONFIG,
	HVPS_SYS_STAT_PID_ON,
	HVPS_SYS_STAT_CAL_GRID_INT_EN,
	NUM_HVPS_SYS_STAT_BITS
};

enum
{
	HVPS_IO_GRID_CLK_STAT = 0,
	HVPS_IO_FIL_CLK_FAULT,
	HVPS_IO_GRID_INT,
	HVPS_IO_BEAM_CTRL,
	HVPS_IO_GRID_STAT,
	HVPS_IO_CAT_ARC,
	HVPS_IO_FAN_FAULT,
	HVPS_IO_PFC_OK,
	HVPS_IO_HV_INT,
	HVPS_IO_HV_STAT,
	HVPS_IO_OC_24_FAULT,
	HVPS_IO_MASTER_FAULT,
	HVPS_IO_OC_HV_FAULT,
	HVPS_IO_TEMP_1_FAULT,
	HVPS_IO_OC_CAT_FAULT,
	HVPS_IO_TEMP_3_FAULT,
	HVPS_IO_TEMP_2_FAULT,
	NUM_HVPS_IO_BITS
};

extern float hvps_expected_val[HVPS_EXPECTED_CNT];
extern float hvps_setpoints[HVPS_SP_CNT];

void check_hvps_values();


#endif /* HVPS_MONITORING_H_ */