/*
*	Empyrean Medical Systems
*	08/2018
*	Project: Gryphon System Control Firmware
*	Module: PC communications parsing
*	Author: Carlton Chow
*	Description:
*/


#ifndef PC_COMM_PARSER_H_
#define PC_COMM_PARSER_H_

#define PC_RX_MIN_COUNT			4
#define PC_RX_BUFFER_SIZE		248
#define PC_TX_BUFFER_SIZE		248

#define PC_SYNC_VAL			0xFFFFFFFFFFFFFFFF

#define PC_PACKET_SYNC_POS	0
#define PC_PACKET_TYPE_POS	8
#define PC_PACKET_ID_POS	12
#define PC_PACKET_COUNT_POS	16
#define PC_PACKET_DATA_POS	20
#define PC_MIN_PACKET_SIZE	24
#define PC_MAX_PACKET_SIZE	100

#define PC_RESPONSE_TYPE_OFFSET	100

#define PC_TELEMETRY_FREQ_MS 10
#define PC_TELEMETRY_PORT	 40020

typedef enum packetType
{
	PCCOM_INVALID_PACKET = 0,
	PCCOM_VERSION_REQUEST,
	PCCOM_FAULT_REQUEST,
	PCCOM_DIRECTIVE_CMD,
	PCCOM_TELEMETERY_REQUEST,
	PCCOM_CONDITION_CMD,
	PCCOM_WARMUP_CMD,
	PCCOM_NEW_SESSION,
	PCCOM_LOAD_OP,
	PCCOM_CONFIRM_OP,
	PCCOM_QUERY_OP,
	PCCOM_TREATMENT_RELEASE,
#if defined(CALIBRATION_MODE)
	CAL_COIL_CMD = 30,
	CAL_HVPS_CMD,
	CAL_DIRECTIVE_CMD,
	CAL_SP_REQ_CMD,
	CAL_MAG_REQ_CMD,
#else
	PCCOM_IMAGING_RELEASE,
	PCCOM_IMAGING_BUTTON_WAIT,
	PCCOM_QC_PING,
	PCCOM_QC_READING,
#endif
	PACKET_TYPE_COUNT
} PacketType_t;

enum pcDirectives
{
	PC_DIR_STARTUP_INIT = 1,
	PC_DIR_STAGE_PLAN,
	PC_DIR_STOP,
	PC_DIR_CLEAR_FAULTS,
	PC_DIR_WIPE_PLAN,
	PC_DIR_RESET_TIMERS,
	PC_DIR_STANDBY,
	PC_DIR_COUNT
};

enum invalidPacketFields
{
	INVALID_RESERVED = 0,
	INVALID_COUNT
};

enum pcVerReqFields
{
	VERSION_REQ_RESERVED = 0,
	VERSION_REQ_COUNT
};

enum pcVerResFields
{
	VERSION_RES_MAJ = 0,
	VERSION_RES_MIN,
	VERSION_RES_LVL,
	VERSION_RES_CRC,
	VERSION_RES_MODE,
	VERSION_RES_COUNT
};

enum faultReqFields
{
	FAULT_REQ_RESERVED = 0,
	FAULT_REQ_COUNT
};

enum faultResFields
{
	FAULT_RES_ID = 0,
	FAULT_RES_ID_DETAIL,
	FAULT_RES_STATE,
	FAULT_RES_TIME,
	FAULT_RES_EXPECTED,
	FAULT_RES_EXPECTED_DETAIL,
	FAULT_RES_TOLERANCE,
	FAULT_RES_MEASURED,
	FAULT_RES_MEASURED_DETAIL,
	FAULT_RES_COUNT
};

enum directiveCmdFields
{
	DIR_CMD_ID = 0,
	DIR_CMD_CONFIRM,
	DIR_CMD_COUNT
};

enum directiveResFields
{
	DIR_RES_STATUS = 0,
	DIR_RES_COUNT	
};

enum telemetryReqFields
{
	TELEMETRY_REQ_RESERVED = 0,
	TELEMETRY_REQ_COUNT
};

enum conditionCmdFields
{
	CONDITION_CMD_FIL = 0,
	CONDITION_CMD_RESERVED,
	CONDITION_CMD_COUNT
};

enum warmupCmdFields
{
	WARMUP_CMD_FIL = 0,
	WARMUP_CMD_COUNT
};

enum newSessionCmdFields
{
	NEW_SES_CMD_POINTS = 0,
	NEW_SES_CMD_ID,
	NEW_SES_CMD_COUNT	
};

enum opCmdFields
{
	OP_CMD_POINT_IDX = 0,
	OP_CMD_TOTAL_TIME,
	OP_CMD_REMAIN_TIME,
	OP_CMD_KV,
	OP_CMD_MA,
	OP_CMD_FIL,
	OP_CMD_X_COIL,
	OP_CMD_Y_COIL,
	OP_CMD_F_COIL,
	OP_CMD_AUTO_EXEC,
	OP_CMD_AUTHENTICATION,
	OP_CMD_COUNT
};


enum opReqFields
{
	OP_REQ_POINT_IDX = 0,
	OP_REQ_COUNT
};

enum epRespFields
{
	OP_RES_STATUS = 0,
	OP_RES_POINT_IDX,
	OP_RES_TOTAL_TIME,
	OP_RES_REMAIN_TIME,
	OP_RES_KV,
	OP_RES_MA,
	OP_RES_FIL,
	OP_RES_X_COIL,
	OP_RES_Y_COIL,
	OP_RES_F_COIL,
	OP_RES_AUTO_EXEC,
	OP_RES_COUNT
};

enum releaseCmdFields
{
	RELEASE_CMD_SCOPE = 0,
	RELEASE_CMD_AUTH,
	RELEASE_CMD_COUNT
};

#if !defined(CALIBRATION_MODE)
enum qcReqFields
{
	QC_REQ_DATA_1 = 0,
	QC_REQ_DATA_2,
	QC_REQ_COUNT	
};

enum qcResFields
{
	QC_RES_DATA_1 = 0,
	QC_RES_DATA_2,
	QC_RES_DATA_3,
	QC_RES_DATA_4,	
	QC_RES_DATA_5,
	QC_RES_COUNT
};
#endif

enum networkConfigFields
{
	NETWORK_BASE_PORT = 0,
	NETWORK_CONSOLE_PORT,
	NETWORK_EXTRA_PORT,
	NETWORK_IP_0,
	NETWORK_IP_1,
	NETWORK_IP_2,
	NETWORK_IP_3,
	NETWORK_SUBNET_0,
	NETWORK_SUBNET_1,
	NETWORK_SUBNET_2,
	NETWORK_SUBNET_3,
	NETWORK_GATEWAY_0,
	NETWORK_GATEWAY_1,
	NETWORK_GATEWAY_2,
	NETWORK_GATEWAY_3,
	NETWORK_CMD_COUNT
};

#if defined(CALIBRATION_MODE)
enum calCoilCmdFields
{
	CAL_COIL_CMD_X = 0,
	CAL_COIL_CMD_Y,
	CAL_COIL_CMD_F,
	CAL_COIL_CMD_COUNT
};

enum calHvpsCmdFields
{
	CAL_HVPS_CMD_FIELD = 0,
	CAL_HVPS_CMD_PARAM_F,
	CAL_HVPS_CMD_PARAM_I,
	CAL_HVPS_CMD_COUNT
};

enum calDirectiveCmdFields
{
	CAL_DIRECTIVE_CMD_COMMAND = 0,
	CAL_DIRECTIVE_CMD_COUNT
};

enum calSetpointReqCmdFields
{
	CAL_SP_REQ_CMD_RESERVED = 0,
	CAL_SP_REQ_CMD_COUNT
};

enum calSetpointResFields
{
	CAL_SP_RES_PWR = 0,
	CAL_SP_RES_KV,
	CAL_SP_RES_MA_LIM,
	CAL_SP_RES_GRID,
	CAL_SP_RES_FIL,
	CAL_SP_RES_COUNT
};
#endif

#if defined(CALIBRATION_MODE)
enum startStopCmdFields
{
	DIRECTIVE_CMD_COMMAND = 0,
	DIRECTIVE_CMD_CONFIRM,
	DIRECTIVE_CMD_RESERVED,
	DIRECTIVE_CMD_MAC,
	DIRECTIVE_CMD_COUNT
};

enum startStopResFields
{
	DIRECTIVE_RES_STATUS = 0,
	DIRECTIVE_RES_RESERVED,
	DIRECTIVE_RES_COUNT
};
#endif

void pc_comm_init();
void process_pc_comm();
void send_pc_response();
void send_telemetry();

#endif /* PC_COMM_PARSER_H_ */