#ifndef SYS_CONFIG_DEFAULTS_H_
#define SYS_CONFIG_DEFAULTS_H_

#include "faults.h"

#if defined(CALIBRATION_MODE)
#define DEFAULT_HS_HIGH			40
#define DEFAULT_HS_MED			35
#define DEFAULT_HS_LOW			30
#define DEFAULT_HS_HYS			2

#define DEFAULT_CAB_HIGH		30
#define DEFAULT_CAB_MED			25
#define DEFAULT_CAB_LOW			20
#define DEFAULT_CAB_HYS			2

#define DEFAULT_PLT_MIN_TEMP	5
#define DEFAULT_PLT_MAX_TEMP	50

#define DEFAULT_WTR_TEMP_ERR	35
#define DEFAULT_HS_TEMP_ERR		50
#define DEFAULT_CAB_TEMP_ERR	40

#define DEFAULT_WTR_P_HI_ERR	6
#define DEFAULT_WTR_P_HI_TH		5
#define DEFAULT_WTR_P_LO_TH		3
#define DEFAULT_WTR_P_LO_ERR	1

#define DEFAULT_WTR_F_HI_ERR	6
#define DEFAULT_WTR_F_HI_TH		5
#define DEFAULT_WTR_F_LO_TH		3
#define DEFAULT_WTR_F_LO_ERR	1

#define DEFAULT_ION_P_HI_TH		6

#define DEFAULT_DEFL_I_TOL		50

#define DEFAULT_DEFL_R			0.3
#define DEFAULT_DEFL_V_TOL		5
#define DEFAULT_FOCUS_I_TOL		150
#define DEFAULT_FOCUS_R			5
#define DEFAULT_FOCUS_V_TOL		100
#define DEFAULT_COIL_HS_ERR		80

#define DEFAULT_MIN_HTR_I		1000
#if MRSRC
#define DEFAULT_WARMUP_I		3500
#define DEFAULT_CONDITION_I		3900
#define HTR_OVERCUR_THRESH		4000
#define DEFAULT_PWR_SP			50
#elif GBSRC
#define DEFAULT_WARMUP_I		2500
#define DEFAULT_CONDITION_I		2900
#define HTR_OVERCUR_THRESH		3250
#define DEFAULT_PWR_SP			400
#endif

#define DEFAULT_HTR_ITOL		5
#define DEFAULT_KV_TOL			5
#define DEFAULT_MA_TOL			5

#define DEFAULT_MA_THRESH		0.2

#else

#define HEATSINK_ERR_TH			50

#define DEFAULT_HS_FULL_TH		40
#define DEFAULT_HS_MED_TH		35
#define DEFAULT_HS_LOW_TH		30
#define DEFAULT_HS_HYS			2

#define DEFAULT_CAB_ERR			40
#define DEFAULT_CAB_FULL		30
#define DEFAULT_CAB_MED			25
#define DEFAULT_CAB_LOW			20
#define DEFAULT_CAB_HYS			2

#define DEFAULT_WTR_P_HI_ERR	6
#define DEFAULT_WTR_P_HI_TH		5
#define DEFAULT_WTR_P_LO_TH		3
#define DEFAULT_WTR_P_LO_ERR	2

#define DEFAULT_ION_P_HI_TH		6

#define DEFAULT_WTR_TEMP_ERR	35

#define DEFAULT_WTR_F_HI_ERR	6
#define DEFAULT_WTR_F_HI_TH		5
#define DEFAULT_WTR_F_LO_TH		3
#define DEFAULT_WTR_F_LO_ERR	2

#define DEFAULT_DEFL_I_TOL	50

#define DEFAULT_DEFL_R		0.3
#define DEFAULT_DEFL_V_TOL	5
#define DEFAULT_FOCUS_I_TOL 150
#define DEFAULT_FOCUS_R		5
#define DEFAULT_FOCUS_V_TOL	100
#define DEFAULT_COIL_HS_ERR	80

#define DEFAULT_MIN_HTR_I	1000

#define DEFAULT_WARMUP_I	2500
#define DEFAULT_CONDITION_I	2900
#define HTR_OVERCUR_THRESH	3250

#define DEFAULT_HTR_ITOL	5
#define DEFAULT_KV_TOL		5
#define DEFAULT_MA_TOL		5

#define DEFAULT_PWR_SP		300

#define DEFAULT_MA_THRESH	0.2

#define QC_MAX_READ		819000
#define QC_MIN_READ		25480
#endif

#endif /* SYS_CONFIG_DEFAULTS_H_ */