#ifndef MCUBOOT_CONFIG_H
#define MCUBOOT_CONFIG_H

#define MCUBOOT_IMAGE_NUMBER 1
#define MCUBOOT_USE_TINYCRYPT 1
#define MCUBOOT_SIGN_EC256 1
#define MCUBOOT_VALIDATE_PRIMARY_SLOT 1
#define MCUBOOT_OVERWRITE_ONLY 1
#define MCUBOOT_SINGLE_APPLICATION_SLOT 1
#define MCUBOOT_SERIAL 1
#define MCUBOOT_SERIAL_WAIT_FOR_DFU 1
#define MCUBOOT_BOOT_MGMT_ECHO 1
#define MCUBOOT_SERIAL_MAX_RECEIVE_SIZE 512
#define MCUBOOT_SERIAL_UNALIGNED_BUFFER_SIZE 64
#define MCUBOOT_PERUSER_MGMT_GROUP_ENABLED 0
#define MCUBOOT_MAX_IMG_SECTORS 90
#define MCUBOOT_BOOT_MAX_ALIGN 4
#define MCUBOOT_DEV_WITH_ERASE 1
#define MCUBOOT_ERASE_PROGRESSIVELY 1
#define MCUBOOT_FIH_PROFILE_OFF 1
#define MCUBOOT_SERIAL_IMG_GRP_HASH 1

#define MCUBOOT_WATCHDOG_FEED() do { } while (0)
#define MCUBOOT_CPU_IDLE() do { } while (0)

#endif