syntax = "proto3";

package com.empyreanmed.heracles.series.v1;

import "com/empyreanmed/heracles/enums/v1/enums.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/timestamp.proto";

// Series is an imaging result in the DICOM format, which is split up to slices.
// Every series is associated with a diagnosis.
message Series {
  // Series id, globally unique
  optional int64 id = 1 [(google.api.field_behavior) = OUTPUT_ONLY];

  // The diagnosis associated with this series
  optional int64 diagnosis_id = 2 [(google.api.field_behavior) = REQUIRED];

  // The visit associated with this series
  optional int64 visit_id = 3 [(google.api.field_behavior) = REQUIRED];

  // Series creation date
  optional google.protobuf.Timestamp creation_date = 4 [(google.api.field_behavior) = OUTPUT_ONLY];

  // Series name
  optional string name = 5;

  // Series image type
  optional com.empyreanmed.heracles.enums.v1.IMAGETYPE type = 6;

  // Series location
  optional string location = 7;

  // Depth of the lesion in millimeters
  optional float lesion_depth = 8;

  // Description of the series
  optional string description = 9;

  // Number of instances in the series
  optional int32 num_of_instances = 10;
}
