syntax = "proto3";

package com.empyreanmed.heracles.series.v1;

import "com/empyreanmed/heracles/series/v1/series.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/field_mask.proto";

// Performs CRUD operations on series.
service SeriesService {
  // Lists series matching request parameters.
  rpc ListSeries(ListSeriesRequest) returns (ListSeriesResponse);

  // Lists series by patient ID matching request parameters.
  rpc ListSeriesByPatientId(ListSeriesByPatientIdRequest) returns (ListSeriesByPatientIdResponse);

  // Streams DICOM files of a given series.
  rpc GetDicom(GetDicomRequest) returns (stream GetDicomResponse);

  // Returns a single series.
  rpc GetSeries(GetSeriesRequest) returns (GetSeriesResponse);

  // Creates a new series.
  rpc CreateSeries(CreateSeriesRequest) returns (CreateSeriesResponse);

  // Updates an existing series.
  rpc UpdateSeries(UpdateSeriesRequest) returns (UpdateSeriesResponse);

  // Deletes a series.
  rpc DeleteSeries(DeleteSeriesRequest) returns (DeleteSeriesResponse);

  // send dicom files to server.
  rpc SendDicom(stream SendDicomRequest) returns (SendDicomResponse);

  // Receive dicom files from server.
  rpc ReceiveDicom(stream ReceiveDicomRequest) returns (ReceiveDicomResponse);
}

// Request message for listing series.
message ListSeriesRequest {
  // Filter by diagnosis.
  optional int64 diagnosis_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the listed series.
message ListSeriesResponse {
  // The series matching the list request. The order is unspecified.
  repeated Series series = 1 [(google.api.field_behavior) = UNORDERED_LIST];
}

// Request message for listing series by patient ID.
message ListSeriesByPatientIdRequest {
  // Filter by patient ID.
  optional int64 patient_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the listed series.
message ListSeriesByPatientIdResponse {
  // The series matching the list request. The order is unspecified.
  repeated Series series = 1 [(google.api.field_behavior) = UNORDERED_LIST];
}

// Request message for fetching DICOM files data.
message GetDicomRequest {
  // The ID of the series whose DICOM files data will be returned.
  optional int64 id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message for fetching DICOM files data.
message GetDicomResponse {
  // Data of a single file in the DICOM format.
  bytes dicom_file_data = 1;

  // The index of the DICOM file in the sequence.
  int32 file_index = 2;
}

// Request message for sending DICOM files data.
message SendDicomRequest {
  // Data of a single file in the DICOM format.
  bytes dicom_file_data = 1;

  // The index of the DICOM file in the sequence.
  int32 file_index = 2;

  // Metadata about the DICOM series (optional, could include patient/series info).
  optional int64 series_id = 3;
}

// Response message for acknowledging the received DICOM files.
message SendDicomResponse {
  // Message indicating whether the upload was successful.
  string message = 1;

  // The total number of files received.
  int32 total_files_received = 2;
}

// Request message for streaming DICOM files.
message ReceiveDicomRequest {
  // The ID of the series whose DICOM files will be streamed.
  optional int64 series_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message for streaming DICOM files.
message ReceiveDicomResponse {
  // Data of a single DICOM file.
  bytes dicom_file_data = 1;

  // The index of the DICOM file in the series.
  int32 file_index = 2;
}

// Request message for fetching a single series.
message GetSeriesRequest {
  // The ID of the series to fetch.
  optional int64 series_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the fetched series.
message GetSeriesResponse {
  // The series with the provided ID.
  Series series = 1;
}

// Request message for creating a new series.
message CreateSeriesRequest {
  // Details of the series to create.
  optional Series series = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the created series.
message CreateSeriesResponse {
  // The series that was created.
  Series series = 1;
}

// Request message for updating an existing series.
message UpdateSeriesRequest {
  // The series to update.
  optional Series series = 1 [(google.api.field_behavior) = REQUIRED];

  // A FieldMask specifying which fields of the series to update.
  optional google.protobuf.FieldMask update_mask = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the updated series.
message UpdateSeriesResponse {
  // The updated series.
  optional Series series = 1;
}

// Request message for deleting a series.
message DeleteSeriesRequest {
  // The ID of the series to delete.
  optional int64 series_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// An empty response message for `DeleteSeries`.
message DeleteSeriesResponse {}
