syntax = "proto3";

package com.empyreanmed.heracles.enums.v1;

// A patient's biological sex.
enum SEXTYPE {
  // UNSPECIFIED value
  SEXTYPE_UNSPECIFIED = 0;

  // Male
  SEXTYPE_MALE = 1;

  // Female
  SEXTYPE_FEMALE = 2;

  // Intersex
  SEXTYPE_INTERSEX = 3;
}

// An enumeration of types of patient identification number types, generally government-issued.
// The patient ID is intended to identify the patient in imaging providers like PACS servers.
enum PATIENTIDTYPE {
  // Default value
  PATIENTIDTYPE_UNSPECIFIED = 0;

  // Social-Security number, generally applicable for permanent US residents
  PATIENTIDTYPE_SSN = 1;

  // Passport number
  PATIENTIDTYPE_PASSPORT = 2;

  // Some other identification scheme
  PATIENTIDTYPE_OTHER = 3;
}

// The type of a target, corresponds to a head or applicator
enum TARGETTYPE {
  // Default value
  TARGETTYPE_UNSPECIFIED = 0;

  // IMVB Collimator 1mm cell
  TARGETTYPE_IMVB_COLLIMATOR_1MM_CELL = 1;

  // IMVB Collimator 2mm cell
  TARGETTYPE_IMVB_COLLIMATOR_2MM_CELL = 2;

  // IMVB Collimator 3mm cell
  TARGETTYPE_IMVB_COLLIMATOR_3MM_CELL = 3;

  // IMVB Collimator 4mm cell
  TARGETTYPE_IMVB_COLLIMATOR_4MM_CELL = 4;

  // IMVB Collimator 5mm cell
  TARGETTYPE_IMVB_COLLIMATOR_5MM_CELL = 5;

  // IMVB Collimator 5cm SSD, 0.5cm field, 0.5mm cell
  TARGETTYPE_IMVB_COLLIMATOR_5CM_SSD_0POINT5CM_FIELD_05MM_CELL = 6;

  // IMVB Collimator 5cm SSD, 1cm field, 1mm cell
  TARGETTYPE_IMVB_COLLIMATOR_5CM_SSD_1CM_FIELD_1MM_CELL = 7;

  // IMVB Collimator 5cm SSD, 1.5cm field, 1mm cell
  TARGETTYPE_IMVB_COLLIMATOR_5CM_SSD_1POINT5CM_FIELD_1MM_CELL = 8;

  // IMVB Collimator 5cm SSD, 2cm field, 1.5mm cell
  TARGETTYPE_IMVB_COLLIMATOR_5CM_SSD_2CM_FIELD_1POINT5MM_CELL = 9;

  // IMVB Collimator 5cm SSD, 3cm field, 1.5mm cell
  TARGETTYPE_IMVB_COLLIMATOR_5CM_SSD_3CM_FIELD_1POINT5MM_CELL = 10;

  // IMVB Collimator, 6MM spot, large central cell 1.5mm cell
  TARGETTYPE_IMVB_COLLIMATOR_6MMSPOT_LARGECENTRAL_CELL = 11;

  // Target Type collimator
  TARGETTYPE_QC_COLLIMATOR = 12;

  // 50mm SSD 15mm field single cell
  TARGETTYPE_50MM_SSD_15MM_FIELD = 13;

  // 50mm SSD 20mm field single cell
  TARGETTYPE_50MM_SSD_20MM_FIELD = 14;

  // 50mm SSD 30mm field single cell
  TARGETTYPE_50MM_SSD_30MM_FIELD = 15;

  // 50mm SSD 40mm field single cell
  TARGETTYPE_50MM_SSD_40MM_FIELD = 16;

  // 50mm SSD 50mm field single cell
  TARGETTYPE_50MM_SSD_50MM_FIELD = 17;
}

// Status of a plan prescription and simulation
enum STATUS {
  // Default value
  STATUS_UNSPECIFIED = 0;

  // Status is pending approval
  STATUS_PENDING_APPROVAL = 1;

  // Status is approved
  STATUS_APPROVED = 2;

  // Status is rejected
  STATUS_REJECTED = 3;
}

// The position of a patient during a procedure or simulation.
enum POSITION {
  // Default value.
  POSITION_UNSPECIFIED = 0;

  // Prone position, patient lying flat on a bed face down.
  POSITION_PRONE = 1;

  // Supine position, patient lying flat on a bed face up.
  POSITION_SUPINE = 2;

  // Sitting position, patient sitting down in a chair.
  POSITION_SITTING = 3;

  // Side-lying position, patient lying down on their right side.
  POSITION_LYING_RT = 4;

  // Side-lying position, patient lying down on their left side.
  POSITION_LYING_LT = 5;

  // Head turned to the left.
  POSITION_HEAD_LEFT = 6;

  // Head turned to the right.
  POSITION_HEAD_RIGHT = 7;
}

// Energy values
enum ENERGY {
  // Unspecified energy
  ENERGY_UNSPECIFIED = 0;
  // 50Kv
  ENERGY_50 = 1;
  // 70Kv
  ENERGY_70 = 2;
  // 100Kv
  ENERGY_100 = 3;
}

// Image types
enum IMAGETYPE {
  // Unspecified image type
  IMAGETYPE_UNSPECIFIED = 0;

  // Xray image type
  IMAGETYPE_XRAY = 1;

  // PhotoAcoustic image type
  IMAGETYPE_PHOTOACOUSTIC = 2;

  //Photosonic image type
  IMAGETYPE_PHOTOSONIC = 3;
}

// Type of medical device used in treatments.
enum DEVICETYPE {
  // Unspecified device type.
  DEVICETYPE_UNSPECIFIED = 0;

  // Custom fabrication device type.
  DEVICETYPE_CUSTOM_FABRICATION = 1;

  // Internal eye device type.
  DEVICETYPE_INTERNAL_EYE = 2;

  // Gamma putty device type.
  DEVICETYPE_GAMMA_PUTTY = 3;

  // External eye device type.
  DEVICETYPE_EXTERNAL_EYE = 4;

  // Ear canal device type.
  DEVICETYPE_EAR_CANAL = 5;

  // Intra-nasal device type.
  DEVICETYPE_INTRA_NASAL = 6;

  // Mastoid device type.
  DEVICETYPE_MASTOID = 7;

  // Dental pacemaker device type.
  DEVICETYPE_DENTAL_PACEMAKER = 8;

  // Lead apron device type.
  DEVICETYPE_LEAD_APRON = 9;

  // Thyroid device type.
  DEVICETYPE_THYROID = 10;

  // Lead glasses device type.
  DEVICETYPE_LEAD_GLASSES = 11;

  // Head holder device type.
  DEVICETYPE_HEAD_HOLDER = 12;

  // Pillow device type.
  DEVICETYPE_PILLOW = 13;

  // Pacemaker shield device type.
  DEVICETYPE_PACEMAKER_SHIELD = 14;

  //Prefabricated shield device type.
  DEVICETYPE_PREFABRICATED_SHIELD = 15;

  // No-shield device type.
  DEVICETYPE_NO_SHIELD = 16;
}

// TREATMENTLOADINGSTATE is an enum for states of treatment loading for plan
enum TREATMENTLOADINGSTATE {
  //Unspecified treatment loading state
  TREATMENTLOADINGSTATE_UNSPECIFIED = 0;
  //Unloaded state for treatment
  TREATMENTLOADINGSTATE_UNLOADED = 1;
  //Pending loading state for treatment
  TREATMENTLOADINGSTATE_PENDINGLOAD = 2;
  //Loaded state for treatment
  TREATMENTLOADINGSTATE_LOADED = 3;
  // A plan is "sent" to external for partial treatment
  TREATMENTLOADINGSTATE_PARTIALPENDINGLOAD = 4;
}

//Field name enum
enum FIELDNAME {
  // N/A
  FIELDNAME_UNSPECIFIED = 0;

  // FW: +4L2   UI: 1
  FIELDNAME_PLUS_4L2 = 1;

  // FW: +4L1   UI: 2
  FIELDNAME_PLUS_4L1 = 2;

  // FW: +4C   UI: 3
  FIELDNAME_PLUS_4C = 3;

  // FW: +4R1  UI: 4
  FIELDNAME_PLUS_4R1 = 4;

  // FW: +4R2   UI: 5
  FIELDNAME_PLUS_4R2 = 5;

  // FW: +3L3 UI: 6
  FIELDNAME_PLUS_3L3 = 6;

  // FW: +3L2 UI: 7
  FIELDNAME_PLUS_3L2 = 7;

  // FW: +3L1 UI: 8
  FIELDNAME_PLUS_3L1 = 8;

  // FW: +3R1 UI: 9
  FIELDNAME_PLUS_3R1 = 9;

  // FW: +3R2 UI: 10
  FIELDNAME_PLUS_3R2 = 10;

  // FW: +3R3 UI: 11
  FIELDNAME_PLUS_3R3 = 11;

  // FW: +2L3 UI: 12
  FIELDNAME_PLUS_2L3 = 12;

  // FW: +2L2 UI: 13
  FIELDNAME_PLUS_2L2 = 13;

  // FW: +2L1 UI: 14
  FIELDNAME_PLUS_2L1 = 14;

  // FW: +2C UI: 15
  FIELDNAME_PLUS_2C = 15;

  // FW: +2R1 UI: 16
  FIELDNAME_PLUS_2R1 = 16;

  // FW: +2R2 UI: 17
  FIELDNAME_PLUS_2R2 = 17;

  // FW: +2R3 UI: 18
  FIELDNAME_PLUS_2R3 = 18;

  // FW: +1L4 UI: 19
  FIELDNAME_PLUS_1L4 = 19;

  // FW: +1L3 UI: 20
  FIELDNAME_PLUS_1L3 = 20;

  // FW: +1L2 UI: 21
  FIELDNAME_PLUS_1L2 = 21;

  // FW: +1L1 UI: 22
  FIELDNAME_PLUS_1L1 = 22;

  // FW: +1R1 UI: 23
  FIELDNAME_PLUS_1R1 = 23;

  // FW: +1R2 UI: 24
  FIELDNAME_PLUS_1R2 = 24;

  // FW: +1R3 UI: 25
  FIELDNAME_PLUS_1R3 = 25;

  // FW: +1R4 UI: 26
  FIELDNAME_PLUS_1R4 = 26;

  // FW: +0L4 UI: 27
  FIELDNAME_PLUS_0L4 = 27;

  // FW: +0L3 UI: 28
  FIELDNAME_PLUS_0L3 = 28;

  // FW: +0L2 UI: 29
  FIELDNAME_PLUS_0L2 = 29;

  // FW: +0L1 UI: 30
  FIELDNAME_PLUS_0L1 = 30;

  // FW: C UI: 31
  FIELDNAME_PLUS_C = 31;

  // FW: +0R1 UI: 32
  FIELDNAME_PLUS_0R1 = 32;

  // FW: +0R2 UI: 33
  FIELDNAME_PLUS_0R2 = 33;

  // FW: +0R3 UI: 34
  FIELDNAME_PLUS_0R3 = 34;

  // FW: +0R4 UI: 35
  FIELDNAME_PLUS_0R4 = 35;

  // FW: -1L4 UI: 36
  FIELDNAME_MINUS_1L4 = 36;

  // FW: -1L3 UI: 37
  FIELDNAME_MINUS_1L3 = 37;

  // FW: -1L2 UI: 38
  FIELDNAME_MINUS_1L2 = 38;

  // FW: -1L1 UI: 39
  FIELDNAME_MINUS_1L1 = 39;

  // FW: -1R1 UI: 40
  FIELDNAME_MINUS_1R1 = 40;

  // FW: -1R2 UI: 41
  FIELDNAME_MINUS_1R2 = 41;

  // FW: -1R3 UI: 42
  FIELDNAME_MINUS_1R3 = 42;

  // FW: -1R4 UI: 43
  FIELDNAME_MINUS_1R4 = 43;

  // FW: -2L3 UI: 44
  FIELDNAME_MINUS_2L3 = 44;

  // FW: -2L2 UI: 45
  FIELDNAME_MINUS_2L2 = 45;

  // FW: -2L1 UI: 46
  FIELDNAME_MINUS_2L1 = 46;

  // FW: -2C UI: 47
  FIELDNAME_MINUS_2C = 47;

  // FW: -2R1 UI: 48
  FIELDNAME_MINUS_2R1 = 48;

  // FW: -2R2 UI: 49
  FIELDNAME_MINUS_2R2 = 49;

  // FW: -2R3 UI: 50
  FIELDNAME_MINUS_2R3 = 50;

  // FW: -3L3 UI: 51
  FIELDNAME_MINUS_3L3 = 51;

  // FW: -3L2 UI: 52
  FIELDNAME_MINUS_3L2 = 52;

  // FW: -3L1 UI: 53
  FIELDNAME_MINUS_3L1 = 53;

  // FW: -3R1 UI: 54
  FIELDNAME_MINUS_3R1 = 54;

  // FW: -3R2 UI: 55
  FIELDNAME_MINUS_3R2 = 55;

  // FW: -3R3 UI: 56
  FIELDNAME_MINUS_3R3 = 56;

  // FW: -4L2 UI: 57
  FIELDNAME_MINUS_4L2 = 57;

  // FW: -4L1 UI: 58
  FIELDNAME_MINUS_4L1 = 58;

  // FW: -4C UI: 59
  FIELDNAME_MINUS_4C = 59;

  // FW: -4R1 UI: 60
  FIELDNAME_MINUS_4R1 = 60;

  // FW: -4R2 UI: 61
  FIELDNAME_MINUS_4R2 = 61;
}

// Enum representing different TDF values.
enum TDF {
  // Default value when TDF is not specified.
  TDF_UNSPECIFIED = 0;

  // TDF value for 94.
  TDF_94 = 1;

  // TDF value for 95.
  TDF_95 = 2;

  // TDF value for 96.
  TDF_96 = 3;

  // TDF value for 97.
  TDF_97 = 4;

  // TDF value for 98.
  TDF_98 = 5;

  // TDF value for 99.
  TDF_99 = 6;

  // TDF value for 100.
  TDF_100 = 7;

  // TDF value for 101.
  TDF_101 = 8;

  // TDF value for 102.
  TDF_102 = 9;
}

//Type of magnetometer enum
enum MAGNETOMETERTYPE {
  //unspecified Type of magnetometer
  MAGNETOMETERTYPE_UNSPECIFIED = 0;
  //back Type of magnetometer
  MAGNETOMETERTYPE_BACK = 1;
  //front Type of magnetometer
  MAGNETOMETERTYPE_FRONT = 2;
}

// SEVERITY is an enum representing various types of treatments.
enum SEVERITY {
  // Unspecified severity type.
  SEVERITY_UNSPECIFIED = 0;

  // info severity type.
  SEVERITY_INFO = 1;

  // warm severity type.
  SEVERITY_WARN = 2;

  // error severity type.
  SEVERITY_ERROR = 3;
}

// LOGTYPE is an enum representing various types of users and systems.
enum LOGTYPE {
  // Unspecified LOGTYPE type.
  LOGTYPE_UNSPECIFIED = 0;

  // System LOGTYPE type.
  LOGTYPE_SYSTEM = 1;

  // User LOGTYPE type.
  LOGTYPE_USER = 2;

  // Error LOGTYPE type.
  LOGTYPE_ERROR = 3;

  // Security LOGTYPE type.
  LOGTYPE_SECURITY = 4;
}

// WARMUPTYPE is an enum representing types of available warmups.
enum WARMUPTYPE {
  // Unspecified warmup type.
  WARMUPTYPE_UNSPECIFIED = 0;
  // Fast warmup type.
  WARMUPTYPE_FAST = 1;
  // Full warmup type.
  WARMUPTYPE_FULL = 2;
}

// PATIENTSTATUS is an enum representing an activity status of a patient
enum PATIENTSTATUS {
  // Unspecified status type.
  PATIENTSTATUS_UNSPECIFIED = 0;
  // active status type.
  PATIENTSTATUS_ACTIVE = 1;
  // inactive status type.
  PATIENTSTATUS_INACTIVE = 2;
  // expired status type.
  PATIENTSTATUS_EXPIRED = 3;
}

// SITELOCATION is an enum representing patient's threaded site location.
enum SITELOCATION {
  // Unspecified site location.
  SITELOCATION_UNSPECIFIED = 0;

  // Breast.
  SITELOCATION_BREAST = 1;

  // Left ear.
  SITELOCATION_LEFT_EAR = 2;

  // Right ear.
  SITELOCATION_RIGHT_EAR = 3;

  // Forehead.
  SITELOCATION_FOREHEAD = 4;

  // Temple.
  SITELOCATION_TEMPLE = 5;

  // Zygoma.
  SITELOCATION_ZYGOMA = 6;

  // Pre-auricular.
  SITELOCATION_PRE_AURICULAR = 7;

  // Cheek.
  SITELOCATION_CHEEK = 8;

  // Chin.
  SITELOCATION_CHIN = 9;

  // Jaw.
  SITELOCATION_JAW = 10;

  // Lip.
  SITELOCATION_LIP = 11;

  // Neck.
  SITELOCATION_NECK = 12;

  // Nose.
  SITELOCATION_NOSE = 13;

  // Scalp.
  SITELOCATION_SCALP = 14;

  // Post-auricular.
  SITELOCATION_POST_AURICULAR = 15;

  // Trunk.
  SITELOCATION_TRUNK = 16;

  // Chest.
  SITELOCATION_CHEST = 17;

  // Abdomen.
  SITELOCATION_ABDOMEN = 18;

  // Back.
  SITELOCATION_BACK = 19;

  // Left lower limb.
  SITELOCATION_LEFT_LOWER_LIMB = 20;

  // Right lower limb.
  SITELOCATION_RIGHT_LOWER_LIMB = 21;

  // Left upper limb.
  SITELOCATION_LEFT_UPPER_LIMB = 22;

  // Right upper limb.
  SITELOCATION_RIGHT_UPPER_LIMB = 23;

  // Right upper eyelid.
  SITELOCATION_RIGHT_UPPER_EYELID = 24;

  // Right lower eyelid.
  SITELOCATION_RIGHT_LOWER_EYELID = 25;

  // Left upper eyelid.
  SITELOCATION_LEFT_UPPER_EYELID = 26;

  // Left lower eyelid.
  SITELOCATION_LEFT_LOWER_EYELID = 27;
}

// PATHOLOGY is an enum representing different types of pathologies.
enum PATHOLOGY {
  // Unspecified pathology.
  PATHOLOGY_UNSPECIFIED = 0;

  // Basal cell carcinoma (BCC).
  PATHOLOGY_BCC = 1;

  // Squamous cell carcinoma (SCC).
  PATHOLOGY_SCC = 2;

  // Squamous cell carcinoma in situ (SCC-IS).
  PATHOLOGY_SCC_IS = 3;

  // Keloid.
  PATHOLOGY_KELOID = 4;

  //BASOSQUAMOUS
  PATHOLOGY_BASOSQUAMOUS = 5;
}

// SSDTYPE is an enum representing different types of source to skin distance.
enum SSDTYPE {
  // Unspecified SSD type
  SSDTYPE_UNSPECIFIED = 0;
  // 50 mm SSD type
  SSDTYPE_50_MM = 1;
  // 30 mm SSD type
  SSDTYPE_30_MM = 2;
}

// Template Type Enum to categorize different medical templates used in treatment planning.
enum TEMPLATETYPE {
  // Default value indicating that the template type is unspecified or not set.
  TEMPLATETYPE_UNSPECIFIED = 0;

  // Template used for simulating lesions, including surrounding margins.
  TEMPLATETYPE_SIMULATION = 1;

  // Template used during treatment planning, such as defining fields and shielding areas.
  TEMPLATETYPE_TREATMENT = 2;

  // Template for follow-up visits or checkups after treatment.
  TEMPLATETYPE_FOLLOWUP = 3;

  // Template for On-Treatment Verification (OTV) or periodic evaluations during treatment.
  TEMPLATETYPE_OTV = 4;

  // Template for other types not covered by the specified categories.
  TEMPLATETYPE_OTHER = 5;
}

// PHOTOTYPE is an enum for photo types.
enum PHOTOTYPE {
  // Unspecified photo type.
  PHOTOTYPE_UNSPECIFIED = 0;

  // Lesion with margin.
  PHOTOTYPE_LESION_WITH_MARGIN = 1;

  // Field with shield.
  PHOTOTYPE_FIELD_WITH_SHIELD = 2;

  // Simulation setup.
  PHOTOTYPE_SIMULATION_SETUP = 3;

  // Identification.
  PHOTOTYPE_IDENTIFICATION = 4;
}

// VISITTYPE is an enum for visit types.
enum VISITTYPE {
  // Unspecified visit type.
  VISITTYPE_UNSPECIFIED = 0;

  // Simulation visit type.
  VISITTYPE_SIMULATION = 1;

  // Treatment visit type.
  VISITTYPE_TREATMENT = 2;

  // On-treatment visit.
  VISITTYPE_OTV = 3;

  // Non-encounter notes.
  VISITTYPE_NON_ENCOUNTER_NOTES = 4;

  // Follow-up visit.
  VISITTYPE_FOLLOW_UP = 5;

  // Skin check visit.
  VISITTYPE_SKIN_CHECK = 6;
}

// CELLTYPE is an enum for cell types.
enum CELLTYPE {
  // Unspecified cell type.
  CELLTYPE_UNSPECIFIED = 0;

  // Aberrant cell type.
  CELLTYPE_ABERRANT = 1;

  // Adenoid cell type.
  CELLTYPE_ADENOID = 2;

  // Atypical Basaloid Proliferation cell type.
  CELLTYPE_ATYPICAL_BASALOID_PROLIFERATION = 3;

  // Basosquamous (Metatypical) cell type.
  CELLTYPE_BASOSQUAMOUS_METATYPICAL = 4;

  // Adnexal Differentiation cell type.
  CELLTYPE_ADNEXAL_DIFFERENTIATION = 5;

  // Squamous Differentiation cell type.
  CELLTYPE_SQUAMOUS_DIFFERENTIATION = 6;

  // Clear Ring cell type.
  CELLTYPE_CLEAR_RING = 7;

  // Cystic Cell Carcinoma cell type.
  CELLTYPE_CYSTIC_CELL_CARCINOMA = 8;

  // Fibroepithelioma of Pinkus cell type.
  CELLTYPE_FIBROEPITHELIOMA_OF_PINKUS = 9;

  // Infiltrative cell type.
  CELLTYPE_INFILTRATIVE = 10;

  // Keratotic cell type.
  CELLTYPE_KERATOTIC = 11;

  // Micro Nodular cell type.
  CELLTYPE_MICRO_NODULAR = 12;

  // Mixed Pattern cell type (BCC + SCC).
  CELLTYPE_MIXED_PATTERN = 13;

  // Morphoeic/Sclerosing/Fibrosing cell type.
  CELLTYPE_MORPHOEIC_SCLEROSING_FIBROSING = 14;

  // Nodular (Classic Basal-Cell) cell type.
  CELLTYPE_NODULAR_CLASSIC_BASAL_CELL = 15;

  // Nodulocystic cell type.
  CELLTYPE_NODULOCYSTIC = 16;

  // Pigmented cell type.
  CELLTYPE_PIGMENTED = 17;

  // Pleomorphic cell type.
  CELLTYPE_PLEOMORPHIC = 18;

  // Polypoid cell type.
  CELLTYPE_POLYPOID = 19;

  // Pore-like cell type.
  CELLTYPE_PORE_LIKE = 20;

  // Rodent Ulcer (Jacobi Ulcer) cell type.
  CELLTYPE_RODENT_ULCER_JACOBI_ULCER = 21;

  // Superficial (Multicentric) cell type.
  CELLTYPE_SUPERFICIAL_MULTICENTRIC = 22;

  // Acantholytic cell type.
  CELLTYPE_ACANTHOLYTIC = 23;

  // Adenoid/Pseudoglandular cell type.
  CELLTYPE_ADENOID_PSEUDOGLANDULAR = 24;

  // Atypical Squamous Proliferation cell type.
  CELLTYPE_ATYPICAL_SQUAMOUS_PROLIFERATION = 25;

  // Basaloid cell type.
  CELLTYPE_BASALOID = 26;

  // Clear-cell cell type.
  CELLTYPE_CLEAR_CELL = 27;

  // Erythroplasia cell type.
  CELLTYPE_ERYTHROPLASIA = 28;

  // Intraepidermal cell type.
  CELLTYPE_INTRAEPIDERMAL = 29;

  // Invasive cell type.
  CELLTYPE_INVASIVE = 30;

  // Keratoacanthoma cell type.
  CELLTYPE_KERATOACANTHOMA = 31;

  // Large Cell Keratinizing cell type.
  CELLTYPE_LARGE_CELL_KERATINIZING = 32;

  // Large Cell Non-Keratinizing cell type.
  CELLTYPE_LARGE_CELL_NON_KERATINIZING = 33;

  // Metaplasia cell type.
  CELLTYPE_METAPLASIA = 34;

  // Moderately Differentiated cell type.
  CELLTYPE_MODERATELY_DIFFERENTIATED = 35;

  // Poorly Differentiated cell type.
  CELLTYPE_POORLY_DIFFERENTIATED = 36;

  // Papillary Carcinoma cell type.
  CELLTYPE_PAPILLARY_CARCINOMA = 37;

  // Signet-ring cell type.
  CELLTYPE_SIGNET_RING_CELL = 38;

  // Small Cell Keratinizing cell type.
  CELLTYPE_SMALL_CELL_KERATINIZING = 39;

  // Superficial cell type.
  CELLTYPE_SUPERFICIAL = 40;

  // Spindle Cell type.
  CELLTYPE_SPINDLE_CELL = 41;

  // Verrucous cell type.
  CELLTYPE_VERRUCOUS = 42;

  // Well-Differentiated cell type.
  CELLTYPE_WELL_DIFFERENTIATED = 43;

  // Superficially Invasive cell type.
  CELLTYPE_SUPERFICIALLY_INVASIVE = 44;

  // Other cell type.
  CELLTYPE_OTHER = 45;

  // None cell type.
  CELLTYPE_NONE = 46;
}

// DESCRIPTION is an enum for description types.
enum DESCRIPTION {
  // Unspecified description type.
  DESCRIPTION_UNSPECIFIED = 0;

  // Infundibulo-cytic description type.
  DESCRIPTION_INFUNDIBULO_CYTIC = 1;

  // Ulcerated long-standing description type.
  DESCRIPTION_ULCERATED_LONG_STANDING = 2;

  // Adenosquamous description type.
  DESCRIPTION_ADENOSQUAMOUS = 3;

  // Desmoplastic/Metaplastic description type.
  DESCRIPTION_DESMOPLASTIC_METAPLASTIC = 4;

  // Recurrent Lesion post-surgery description type.
  DESCRIPTION_RECURRENT_LESION_POST_SURGERY = 5;

  // Large Lesion description type.
  DESCRIPTION_LARGE_LESION = 6;

  // Deep Lesion description type.
  DESCRIPTION_DEEP_LESION = 7;

  // Rapid growth description type.
  DESCRIPTION_RAPID_GROWTH = 8;

  // Extension into hair follicle description type.
  DESCRIPTION_EXTENSION_INTO_HAIR_FOLLICLE = 9;
}

// ICDCODE is an enum for ICD codes.
enum ICDCODE {
  // Unspecified ICD code.
  ICDCODE_UNSPECIFIED = 0;

  // BCC Breast ICD code.
  ICDCODE_BCC_BREAST = 1;

  // SCC Breast ICD code.
  ICDCODE_SCC_BREAST = 2;

  // SCC-IS Breast ICD code.
  ICDCODE_SCC_IS_BREAST = 3;

  // BCC Left Ear ICD code.
  ICDCODE_BCC_LEFT_EAR = 4;

  // SCC Left Ear ICD code.
  ICDCODE_SCC_LEFT_EAR = 5;

  // SCC-IS Left Ear ICD code.
  ICDCODE_SCC_IS_LEFT_EAR = 6;

  // BCC Right Ear ICD code.
  ICDCODE_BCC_RIGHT_EAR = 7;

  // SCC Right Ear ICD code.
  ICDCODE_SCC_RIGHT_EAR = 8;

  // SCC-IS Right Ear ICD code.
  ICDCODE_SCC_IS_RIGHT_EAR = 9;

  // BCC Face ICD code.
  // *Including BCC in other parts of the face, such as Cheek, Chin, Forehead, Jaw, Pre-Auricular and Zygoma.
  ICDCODE_BCC_FACE = 10;

  // SCC Face ICD code.
  // *Including SCC in other parts of the face, such as Cheek, Chin, Forehead, Jaw, Pre-Auricular and Zygoma.
  ICDCODE_SCC_FACE = 11;

  // SCC-IS Face ICD code.
  // *Including SCC-IS in other parts of the face, such as Cheek, Chin, Forehead, Jaw, Pre-Auricular and Zygoma.
  ICDCODE_SCC_IS_FACE = 12;

  // BCC Lip ICD code.
  ICDCODE_BCC_LIP = 13;

  // SCC Lip ICD code.
  ICDCODE_SCC_LIP = 14;

  // SCC-IS Lip ICD code.
  ICDCODE_SCC_IS_LIP = 15;

  // BCC Neck ICD code.
  ICDCODE_BCC_NECK = 16;

  // SCC Neck ICD code.
  ICDCODE_SCC_NECK = 17;

  // SCC-IS Neck ICD code.
  ICDCODE_SCC_IS_NECK = 18;

  // BCC Nose ICD code.
  // *Including BCC in specific parts of the nose, such as the Ala, the bridge, the tip and root.
  ICDCODE_BCC_NOSE = 19;

  // SCC Nose ICD code.
  // *Including SCC in specific parts of the nose, such as the Ala, the bridge, the tip and root.
  ICDCODE_SCC_NOSE = 20;

  // SCC-IS Nose ICD code.
  // *Including SCC-IS in specific parts of the nose, such as the Ala, the bridge, the tip and root.
  ICDCODE_SCC_IS_NOSE = 21;

  // BCC Scalp ICD code.
  // *Same for BCC_PostAuricular.
  ICDCODE_BCC_SCALP = 22;

  // SCC Scalp ICD code.
  // *Same for SCC_PostAuricular.
  ICDCODE_SCC_SCALP = 23;

  // SCC-IS Scalp ICD code.
  // *Same for SCC_IS_PostAuricular.
  ICDCODE_SCC_IS_SCALP = 24;

  // BCC PostAuricular ICD code.
  // *Same for BCC_Scalp.
  ICDCODE_BCC_POSTAURICULAR = 25;

  // SCC PostAuricular ICD code.
  // *Same for SCC_Scalp.
  ICDCODE_SCC_POSTAURICULAR = 26;

  // SCC-IS PostAuricular ICD code.
  // *Same for SCC_IS_Scalp.
  ICDCODE_SCC_IS_POSTAURICULAR = 27;

  // BCC Trunk ICD code.
  // *Same for BCC_Chest, BCC_Abdomen and BCC_Back.
  ICDCODE_BCC_TRUNK = 28;

  // SCC Trunk ICD code.
  // *Same for SCC_Chest, SCC_Abdomen and SCC_Back.
  ICDCODE_SCC_TRUNK = 29;

  // SCC-IS Trunk ICD code.
  // *Same for SCC_IS_Chest, SCC_IS_Abdomen and SCC_IS_Back.
  ICDCODE_SCC_IS_TRUNK = 30;

  // BCC Chest ICD code.
  // *Same for BCC_Trunk, BCC_Abdomen and BCC_Back.
  ICDCODE_BCC_CHEST = 31;

  // SCC Chest ICD code.
  // *Same for SCC_Trunk, SCC_Abdomen and SCC_Back.
  ICDCODE_SCC_CHEST = 32;

  // SCC-IS Chest ICD code.
  // *Same for SCC_IS_Trunk, SCC_IS_Abdomen and SCC_IS_Back.
  ICDCODE_SCC_IS_CHEST = 33;

  // BCC Abdomen ICD code.
  // *Same for BCC_Trunk, BCC_Chest and BCC_Back.
  ICDCODE_BCC_ABDOMEN = 34;

  // SCC Abdomen ICD code.
  // *Same for SCC_Trunk, SCC_Chest and SCC_Back.
  ICDCODE_SCC_ABDOMEN = 35;

  // SCC-IS Abdomen ICD code.
  // *Same for BCC_Trunk, BCC_Chest and BCC_Back.
  ICDCODE_SCC_IS_ABDOMEN = 36;

  // BCC Back ICD code.
  // *Same for BCC_Trunk, BCC_Abdomen and BCC_Chest.
  ICDCODE_BCC_BACK = 37;

  // SCC Back ICD code.
  // *Same for SCC_Trunk, SCC_Abdomen and SCC_Chest.
  ICDCODE_SCC_BACK = 38;

  // SCC-IS Back ICD code.
  // *Same for SCC_IS_Trunk, SCC_IS_Abdomen and SCC_IS_Chest.
  ICDCODE_SCC_IS_BACK = 39;

  // BCC Left Lower Limb ICD code.
  // *Including BCC in the left hip.
  ICDCODE_BCC_LEFT_LOWER_LIMB = 40;

  // SCC Left Lower Limb ICD code.
  // *Including SCC in the left hip.
  ICDCODE_SCC_LEFT_LOWER_LIMB = 41;

  // SCC-IS Left Lower Limb ICD code.
  // *Including SCC-IS in the left hip.
  ICDCODE_SCC_IS_LEFT_LOWER_LIMB = 42;

  // BCC Right Lower Limb ICD code.
  // *Including BCC in the right hip.
  ICDCODE_BCC_RIGHT_LOWER_LIMB = 43;

  // SCC Right Lower Limb ICD code.
  // *Including SCC in the right hip.
  ICDCODE_SCC_RIGHT_LOWER_LIMB = 44;

  // SCC-IS Right Lower Limb ICD code.
  // *Including SCC-IS in the right hip.
  ICDCODE_SCC_IS_RIGHT_LOWER_LIMB = 45;

  // BCC Left Upper Limb ICD code.
  // *Including BCC in the left shoulder.
  ICDCODE_BCC_LEFT_UPPER_LIMB = 46;

  // SCC Left Upper Limb ICD code.
  // *Including SCC in the left shoulder.
  ICDCODE_SCC_LEFT_UPPER_LIMB = 47;

  // SCC-IS Left Upper Limb ICD code.
  // *Including SCC-IS in the left shoulder.
  ICDCODE_SCC_IS_LEFT_UPPER_LIMB = 48;

  // BCC Right Upper Limb ICD code.
  // *Including BCC in the right shoulder.
  ICDCODE_BCC_RIGHT_UPPER_LIMB = 49;

  // SCC Right Upper Limb ICD code.
  // *Including SCC in the right shoulder.
  ICDCODE_SCC_RIGHT_UPPER_LIMB = 50;

  // SCC-IS Right Upper Limb ICD code.
  // *Including SCC-IS in the right shoulder.
  ICDCODE_SCC_IS_RIGHT_UPPER_LIMB = 51;

  // BCC Right Upper Eyelid ICD code.
  ICDCODE_BCC_RIGHT_UPPER_EYELID = 52;

  // SCC Right Upper Eyelid ICD code.
  ICDCODE_SCC_RIGHT_UPPER_EYELID = 53;

  // SCC-IS Right Upper Eyelid ICD code.
  ICDCODE_SCC_IS_RIGHT_UPPER_EYELID = 54;

  // BCC Right Lower Eyelid ICD code.
  // *Including BCC in the right Canthus.
  ICDCODE_BCC_RIGHT_LOWER_EYELID = 55;

  // SCC Right Lower Eyelid ICD code.
  // *Including SCC in the right Canthus.
  ICDCODE_SCC_RIGHT_LOWER_EYELID = 56;

  // SCC-IS Right Lower Eyelid ICD code.
  // *Including SCC-IS in the right Canthus.
  ICDCODE_SCC_IS_RIGHT_LOWER_EYELID = 57;

  // BCC Left Upper Eyelid ICD code.
  ICDCODE_BCC_LEFT_UPPER_EYELID = 58;

  // SCC Left Upper Eyelid ICD code.
  ICDCODE_SCC_LEFT_UPPER_EYELID = 59;

  // SCC-IS Left Upper Eyelid ICD code.
  ICDCODE_SCC_IS_LEFT_UPPER_EYELID = 60;

  // BCC Left Lower Eyelid ICD code.
  // *Including BCC in the left Canthus.
  ICDCODE_BCC_LEFT_LOWER_EYELID = 61;

  // SCC Left Lower Eyelid ICD code.
  // *Including SCC in the left Canthus.
  ICDCODE_SCC_LEFT_LOWER_EYELID = 62;

  // SCC-IS Left Lower Eyelid ICD code.
  // *Including SCC-IS in the left Canthus.
  ICDCODE_SCC_IS_LEFT_LOWER_EYELID = 63;

  // Basosquamous Breast ICD code.
  ICDCODE_BASOSQUAMOUS_BREAST = 64;

  // Basosquamous Left Ear ICD code.
  ICDCODE_BASOSQUAMOUS_LEFT_EAR = 65;

  // Basosquamous Right Ear ICD code.
  ICDCODE_BASOSQUAMOUS_RIGHT_EAR = 66;

  // Basosquamous Face ICD code.
  // *Including Basosquamous in other parts of the face, such as Cheek, Chin, Forehead, Jaw, Pre-Auricular and Zygoma.
  ICDCODE_BASOSQUAMOUS_FACE = 67;

  // Basosquamous Lip ICD code.
  ICDCODE_BASOSQUAMOUS_LIP = 68;

  // Basosquamous Neck ICD code.
  ICDCODE_BASOSQUAMOUS_NECK = 69;

  // Basosquamous Nose ICD code.
  // *Including Basosquamous in specific parts of the nose, such as the Ala, the bridge, the tip and root.
  ICDCODE_BASOSQUAMOUS_NOSE = 70;

  // Basosquamous Scalp ICD code.
  // *Same as BCC_Scalp, SCC_Scalp, SCC-IS_Scalp for location references.
  ICDCODE_BASOSQUAMOUS_SCALP = 71;

  // Basosquamous PostAuricular ICD code.
  // *Same as BCC_PostAuricular, SCC_PostAuricular, SCC-IS_PostAuricular for location references.
  ICDCODE_BASOSQUAMOUS_POSTAURICULAR = 72;

  // Basosquamous Trunk ICD code.
  // *Same as BCC_Trunk, SCC_Trunk, SCC-IS_Trunk for location references.
  ICDCODE_BASOSQUAMOUS_TRUNK = 73;

  // Basosquamous Chest ICD code.
  // *Same as BCC_Chest, SCC_Chest, SCC-IS_Chest for location references.
  ICDCODE_BASOSQUAMOUS_CHEST = 74;

  // Basosquamous Abdomen ICD code.
  // *Same as BCC_Abdomen, SCC_Abdomen, SCC-IS_Abdomen for location references.
  ICDCODE_BASOSQUAMOUS_ABDOMEN = 75;

  // Basosquamous Back ICD code.
  // *Same as BCC_Back, SCC_Back, SCC-IS_Back for location references.
  ICDCODE_BASOSQUAMOUS_BACK = 76;

  // Basosquamous Left Lower Limb ICD code.
  // *Including Basosquamous in the left hip.
  ICDCODE_BASOSQUAMOUS_LEFT_LOWER_LIMB = 77;

  // Basosquamous Right Lower Limb ICD code.
  // *Including Basosquamous in the right hip.
  ICDCODE_BASOSQUAMOUS_RIGHT_LOWER_LIMB = 78;

  // Basosquamous Left Upper Limb ICD code.
  // *Including Basosquamous in the left shoulder.
  ICDCODE_BASOSQUAMOUS_LEFT_UPPER_LIMB = 79;

  // Basosquamous Right Upper Limb ICD code.
  // *Including Basosquamous in the right shoulder.
  ICDCODE_BASOSQUAMOUS_RIGHT_UPPER_LIMB = 80;

  // Basosquamous Right Upper Eyelid ICD code.
  ICDCODE_BASOSQUAMOUS_RIGHT_UPPER_EYELID = 81;

  // Basosquamous Right Lower Eyelid ICD code.
  ICDCODE_BASOSQUAMOUS_RIGHT_LOWER_EYELID = 82;

  // Basosquamous Left Upper Eyelid ICD code.
  ICDCODE_BASOSQUAMOUS_LEFT_UPPER_EYELID = 83;

  // Basosquamous Left Lower Eyelid ICD code.
  ICDCODE_BASOSQUAMOUS_LEFT_LOWER_EYELID = 84;

  //No ICD code
  ICDCODE_NONE = 85;
}

// Permission enum.
enum PERMISSION {
  // Unspecified permission.
  PERMISSION_UNSPECIFIED = 0;

  // Permission to handle patient clinical data.
  PERMISSION_PATIENTS_CLINICAL_DATA = 1;

  // Permission to handle patient treatments.
  PERMISSION_PATIENTS_TREATMENT = 2;

  // Permission for system calibration.
  PERMISSION_SYSTEM_CALIBRATION = 3;

  // Permission for quality assurance.
  PERMISSION_QUALITY_ASSURANCE = 4;

  // Permission for system settings.
  PERMISSION_SYSTEM_SETTINGS = 5;

  // Permission for user management.
  PERMISSION_USER_MANAGEMENT = 6;

  // Permission for services usage.
  PERMISSION_SERVICES = 7;
}
