#ifndef SYSFLASH_H
#define SYSFLASH_H

#define FLASH_DEVICE_INTERNAL_FLASH 0
#define FLASH_AREA_BOOTLOADER 0
#define FLASH_AREA_IMAGE_0_PRIMARY 1
#define FLASH_AREA_IMAGE_0_SECONDARY 2

#define FLASH_AREA_IMAGE_PRIMARY(x) ((x) == 0 ? FLASH_AREA_IMAGE_0_PRIMARY : 255)
#define FLASH_AREA_IMAGE_SECONDARY(x) ((x) == 0 ? FLASH_AREA_IMAGE_0_PRIMARY : 255)

#endif