/**
 * @file led_ring.c
 * @brief Implementation of the LED ring driver, TIM2 Channel 1 only.
 */

#include "led_ring.h"
#include <math.h>
#include "main.h"
#include "timer.h"

/* TIM2 handle is generated by CubeMX in main.c / tim.c */
extern TIM_HandleTypeDef htim2;

#define LED_RING_TIMER     (&htim2)
#define LED_RING_CHANNEL   TIM_CHANNEL_1

static uint8_t  s_current_pct = 0;
static bool     s_initialized = false;

/* ---- fade state ---- */
static volatile bool     s_fade_active   = false;
static uint8_t            s_fade_from_pct = 0;
static uint8_t            s_fade_to_pct   = 0;
static uint16_t           s_fade_duration_ms = 0;
static uint16_t           s_fade_elapsed_ms  = 0;

/* ---- breathe state ---- */
static uint32_t s_breathe_phase_ms = 0;

volatile int32_t led_ring_ms;

bool init_led_ring(void)
{
    if (HAL_TIM_PWM_Start(LED_RING_TIMER, LED_RING_CHANNEL) != HAL_OK) {
        return false;
    }

    s_initialized = true;
    s_current_pct = 0;
    led_ring_set_duty_raw(0);   /* start dark */

    return true;
}

void led_ring_set_duty_raw(uint32_t duty)
{
    if (!s_initialized) {
        return;
    }
    if (duty > LED_RING_PWM_MAX) {
        duty = LED_RING_PWM_MAX;
    }
    __HAL_TIM_SET_COMPARE(LED_RING_TIMER, LED_RING_CHANNEL, duty);
}

void led_ring_set_brightness(uint8_t percent)
{
    if (percent > 100) {
        percent = 100;
    }
    s_current_pct = percent;

    /* percent -> raw duty, rounded */
    uint32_t duty = ((uint32_t)percent * LED_RING_PWM_MAX + 50) / 100;

    led_ring_set_duty_raw(duty);
}

uint8_t led_ring_get_brightness(void)
{
    return s_current_pct;
}

void led_ring_turn_off(void)
{
    led_ring_set_duty_raw(0);
}

void led_ring_turn_on(void)
{
    uint8_t pct = (s_current_pct == 0) ? 100 : s_current_pct;
    led_ring_set_brightness(pct);
}

static led_ring_mode_t s_current_mode = LED_RING_MODE_OFF;

void led_ring_set_mode(led_ring_mode_t mode)
{
    s_current_mode = mode;

    switch (mode) {
        case LED_RING_MODE_OFF:
            led_ring_turn_off();
            break;

        case LED_RING_MODE_DIM:
            led_ring_set_brightness(LED_RING_DIM_PCT);
            break;

        case LED_RING_MODE_NORMAL:
            led_ring_set_brightness(LED_RING_NORMAL_PCT);
            break;

        case LED_RING_MODE_HIGH:
            led_ring_set_brightness(LED_RING_HIGH_PCT);
            break;

        case LED_RING_MODE_BREATHING:
            /* actual animation is driven by led_ring_update_mode() */
            break;

        default:
            break;
    }
}

/**
 * @brief Arm a non-blocking fade. Actual stepping happens in
 *        led_ring_tick(), called from your timer ISR with the
 *        elapsed tick period each time.
 */
void led_ring_fade_to(uint8_t from_pct, uint8_t to_pct, uint16_t duration_ms)
{
    if (!s_initialized) {
        return;
    }
    if (from_pct > 100) from_pct = 100;
    if (to_pct   > 100) to_pct   = 100;

    s_fade_from_pct    = from_pct;
    s_fade_to_pct      = to_pct;
    s_fade_duration_ms = (duration_ms == 0) ? 1 : duration_ms; /* avoid div-by-0 */
    s_fade_elapsed_ms  = 0;

    led_ring_set_brightness(from_pct);
    s_fade_active = true;
}

bool led_ring_is_fading(void)
{
    return s_fade_active;
}

/**
 * @brief Advance the breathing animation by tick_ms of phase.
 *        Called internally from led_ring_tick() when mode is BREATHING.
 */
static void led_ring_breathe_tick(uint16_t tick_ms)
{
    s_breathe_phase_ms = (s_breathe_phase_ms + tick_ms) % LED_RING_BREATHE_PERIOD_MS;

    float phase_norm = (float)s_breathe_phase_ms / (float)LED_RING_BREATHE_PERIOD_MS;
    float wave = (1.0f - cosf(2.0f * (float)M_PI * phase_norm)) / 2.0f;

    uint8_t pct = (uint8_t)(wave * LED_RING_MAX_BREATH_PCT);
    led_ring_set_brightness(pct);
}

/**
 * @brief Master animation tick - call this from your timer ISR (or
 *        scheduler) with the elapsed time since the last call.
 *        Advances whichever animation is currently active (fade or breathe).
 *
 * @param tick_ms  Elapsed time in milliseconds since the last call to this
 *                 function. Passed through to the fade/breathe step logic
 *                 so animation timing is correct regardless of call rate.
 */
void led_ring_tick(uint16_t tick_ms)
{
    if (led_ring_ms < 0) {
        led_ring_ms = tick_ms;
    
        if (!s_initialized) {
            return;
        }

        if (s_fade_active) {
            s_fade_elapsed_ms += tick_ms;

            if (s_fade_elapsed_ms >= s_fade_duration_ms) {
                led_ring_set_brightness(s_fade_to_pct);
                s_fade_active = false;
            } else {
                int16_t diff = (int16_t)s_fade_to_pct - (int16_t)s_fade_from_pct;
                int16_t pct = (int16_t)s_fade_from_pct +
                            (diff * (int32_t)s_fade_elapsed_ms) / s_fade_duration_ms;
                led_ring_set_brightness((uint8_t)pct);
            }
            return; /* fade takes priority over breathing */
        }

        if (s_current_mode == LED_RING_MODE_BREATHING) {
            led_ring_breathe_tick(tick_ms);
        }
    }
}
