/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAME70 has 4 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3

#define IO_EXT_WD_RST GPIO(GPIO_PORTA, 0)
#define IO_INDICATORS_EN GPIO(GPIO_PORTA, 1)
#define IO_TIMERS_STARTn GPIO(GPIO_PORTA, 2)
#define PA3 GPIO(GPIO_PORTA, 3)
#define PA4 GPIO(GPIO_PORTA, 4)
#define PA5 GPIO(GPIO_PORTA, 5)
#define PA6 GPIO(GPIO_PORTA, 6)
#define IO_QC_EN GPIO(GPIO_PORTA, 8)
#define PA9 GPIO(GPIO_PORTA, 9)
#define PA10 GPIO(GPIO_PORTA, 10)
#define IO_HVPS_RDYn GPIO(GPIO_PORTA, 11)
#define IO_HVPS_WARNING GPIO(GPIO_PORTA, 12)
#define IO_AC_FAULT GPIO(GPIO_PORTA, 13)
#define IO_HV_ON GPIO(GPIO_PORTA, 14)
#define IO_GRID_OFF GPIO(GPIO_PORTA, 15)
#define IO_HV_EN GPIO(GPIO_PORTA, 16)
#define IO_GRID_ENn GPIO(GPIO_PORTA, 17)
#define IO_EMISSION_EN GPIO(GPIO_PORTA, 18)
#define IO_HS_FAN_EN GPIO(GPIO_PORTA, 19)
#define IO_CB_FAN_EN GPIO(GPIO_PORTA, 20)
#define IO_PUMP_EN GPIO(GPIO_PORTA, 21)
#define IO_ION_PUMP_EN GPIO(GPIO_PORTA, 23)
#define IO_ION_REPELLER_EN GPIO(GPIO_PORTA, 24)
#define PA25 GPIO(GPIO_PORTA, 25)
#define PA26 GPIO(GPIO_PORTA, 26)
#define PA27 GPIO(GPIO_PORTA, 27)
#define PA28 GPIO(GPIO_PORTA, 28)
#define CARD_DETECT_0 GPIO(GPIO_PORTA, 29)
#define PA30 GPIO(GPIO_PORTA, 30)
#define PA31 GPIO(GPIO_PORTA, 31)
#define PB0 GPIO(GPIO_PORTB, 0)
#define PB1 GPIO(GPIO_PORTB, 1)
#define IO_COIL_X_DIRn GPIO(GPIO_PORTB, 2)
#define IO_COIL_Y_DIRn GPIO(GPIO_PORTB, 3)
#define IO_DOOR_CLOSED GPIO(GPIO_PORTC, 0)
#define IO_DRIVE_SYS_LOCKED GPIO(GPIO_PORTC, 1)
#define IO_BASE_ESTOPn GPIO(GPIO_PORTC, 2)
#define IO_REMOTE_ESTOPn GPIO(GPIO_PORTC, 3)
#define IO_KUKA_FAULT_1n GPIO(GPIO_PORTC, 4)
#define IO_KUKA_FAULT_2n GPIO(GPIO_PORTC, 5)
#define IO_WATER_LEVEL GPIO(GPIO_PORTC, 6)
#define IO_ION_PUMP_HVON GPIO(GPIO_PORTC, 7)
#define IO_TIMER_FAULT_1n GPIO(GPIO_PORTC, 8)
#define IO_TIMER_FAULT2n GPIO(GPIO_PORTC, 9)
#define IO_HVPS_FAULTn GPIO(GPIO_PORTC, 10)
#define IO_COOLER_FAULTn GPIO(GPIO_PORTC, 11)
#define IO_WATER_TEMP_FAULTn GPIO(GPIO_PORTC, 12)
#define IO_WD_FAULTn GPIO(GPIO_PORTC, 13)
#define IO_MCU_FAULTn GPIO(GPIO_PORTC, 14)
#define SPARE_INTERLOCK_1 GPIO(GPIO_PORTC, 15)
#define IO_MASTER_FAULTn GPIO(GPIO_PORTC, 16)
#define IO_CLEAR_FAULT GPIO(GPIO_PORTC, 17)
#define IO_REMOTE_KEY GPIO(GPIO_PORTC, 18)
#define IO_BASE_KEY GPIO(GPIO_PORTC, 19)
#define IO_COIL_DAC_LDACn GPIO(GPIO_PORTC, 20)
#define IO_COIL_DAC_CLRn GPIO(GPIO_PORTC, 21)
#define IO_COIL_DAC_RDYn GPIO(GPIO_PORTC, 22)
#define IO_COIL_DAC_CSn GPIO(GPIO_PORTC, 23)
#define PC24 GPIO(GPIO_PORTC, 24)
#define PC26 GPIO(GPIO_PORTC, 26)
#define PC27 GPIO(GPIO_PORTC, 27)
#define IO_FAN_DAC_LDACn GPIO(GPIO_PORTC, 28)
#define IO_FAN_DAC_CLRn GPIO(GPIO_PORTC, 29)
#define IO_FAN_DAC_RDYn GPIO(GPIO_PORTC, 30)
#define IO_FAN_DAC_CSn GPIO(GPIO_PORTC, 31)
#define PD0 GPIO(GPIO_PORTD, 0)
#define PD1 GPIO(GPIO_PORTD, 1)
#define PD2 GPIO(GPIO_PORTD, 2)
#define PD3 GPIO(GPIO_PORTD, 3)
#define PD4 GPIO(GPIO_PORTD, 4)
#define PD5 GPIO(GPIO_PORTD, 5)
#define PD6 GPIO(GPIO_PORTD, 6)
#define PD7 GPIO(GPIO_PORTD, 7)
#define PD8 GPIO(GPIO_PORTD, 8)
#define PD9 GPIO(GPIO_PORTD, 9)
#define PHY_RESET_PIN GPIO(GPIO_PORTD, 10)
#define IO_LED1 GPIO(GPIO_PORTD, 12)
#define IO_LED2 GPIO(GPIO_PORTD, 13)
#define IO_LED3 GPIO(GPIO_PORTD, 14)
#define IO_LED4 GPIO(GPIO_PORTD, 15)
#define IO_LED5 GPIO(GPIO_PORTD, 16)
#define IO_LED6 GPIO(GPIO_PORTD, 17)			//REMOTE_LED_X
#define PD18 GPIO(GPIO_PORTD, 18)
#define PD19 GPIO(GPIO_PORTD, 19)
#define PD25 GPIO(GPIO_PORTD, 25)
#define PD26 GPIO(GPIO_PORTD, 26)
#define PD27 GPIO(GPIO_PORTD, 27)
#define PD28 GPIO(GPIO_PORTD, 28)
#define IO_REMOTE_LED_1 GPIO(GPIO_PORTD, 29)
#define IO_REMOTE_LED_2 GPIO(GPIO_PORTD, 30)

#endif // ATMEL_START_PINS_H_INCLUDED
