openapi: 3.0.3

info:
  title: DeepColor GentleBeam API
  description: |
    API for communication between DeepColor imaging system GentleBeam central place.
    This is the API to be used by the GentleBeam software to communicate with the DeepColor software.
  version: '1.0'

servers:
  - url: http://0.0.0.0:33500/apiV1
  
tags:
  - name: General
    description: General Endpoints
  - name: Patient
    description: Endpoints for patient folder management. A patient folder contains the deepcolor "Study" and all related data.
  - name: Site
    description: Endpoints for site management. A site is a skin site/session where images are taken. In practice a site is a deepcolor "Session" according to deepcolor database terminology.
  - name: Acquisition
    description: Endpoints for image management. An acquisition is a deepcolor "AcquisitionGroup" according to deepcolor database terminology.
  - name: Measurements
    description: Endpoints for measurement management
    
### PATHS ###
paths:
  
  # GENERAL ENDPOINTS
  /test:
    get:
      tags:
        - General
      summary: Test API connectivity
      description: Tests if the API is reachable and returns a simple message.
      responses:
        '200':
          description: API is reachable
  
  /status:
    get:
      tags:
        - General
      summary: Get current status
      description: Retrieves the current status including patientName, sitesList with each acqusition, the currently loaded session, and the currently loaded acquisition.
      responses:
        '200':
          description: Current status information
          content:
            application/json:
              schema:
                type: object
                properties:
                  patientName:
                    type: string
                    description: Current patient name
                  sitesList:
                    type: array
                    description: List of all sites/sessions
                    items:
                      type: object
                      properties:
                        siteId:
                          type: integer
                        siteName:
                          type: string
                  currentSite:
                    type: object
                    description: Currently loaded site/session
                    properties:
                      siteId:
                        type: integer
                      siteName:
                        type: string
                  currentAcq:
                    type: object
                    description: Currently loaded acquisition
                    properties:
                      acqId:
                        type: integer
                      acqName:
                          type: string
                      acqDate:
                          type: long
                      acqPreviewPath:
                          type: string
                example:
                  patientName: "patient_42"
                  sitesList:
                    - siteId: 1
                      siteName: Nose 12
                      acqs:
                        - acqId: 1
                          acqName: "Visit 18/09/2025 - 08:50:25"
                          acqDate: 1760691258998
                          acqPreviewPath: "/path/to/preview/image_1.png"
                        - acqId: 2
                          acqName: "Visit 20/09/2025 - 10:15:42"
                          acqDate: 1760860542000
                          acqPreviewPath: "/path/to/preview/image_2.png"
                    - siteId: 2
                      siteName: Ear 13
                      acqs:
                        - acqId: 3
                          acqName: "Visit 19/09/2025 - 14:22:10"
                          acqDate: 1760786530000
                          acqPreviewPath: "/path/to/preview/image_3.png"
                    - siteId: 3
                      siteName: Chin left side 14
                      acqs:
                        - acqId: 4
                          acqName: "Visit 21/09/2025 - 09:05:33"
                          acqDate: 1760946333000
                          acqPreviewPath: "/path/to/preview/image_4.png"
                        - acqId: 5
                          acqName: "Visit 22/09/2025 - 11:47:58"
                          acqDate: 1761030478000
                          acqPreviewPath: "/path/to/preview/image_5.png"
                        - acqId: 6
                          acqName: "Visit 23/09/2025 - 11:48:12"
                          acqDate: 1761119292000
                          acqPreviewPath: "/path/to/preview/image_6.png"
                  currentSite:
                    siteId: 2
                    siteName: Ear 13
                  currentAcq:
                    acqId: 3
                    acqName: "Visit 19/09/2025 - 14:22:10"
                    acqDate: 1760786530000
                    acqPreviewPath: "/path/to/preview/image_3.png"
        '404':
          description: No patient loaded

  /version:
    get:
      tags:
        - General
      summary: Get application version
      description: Retrieves the current version of the application.
      responses:
        '200':
          description: Current application version
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    description: Current application version
                example:
                  version: "1.0.0"
                  
  # PATIENT ENDPOINTS
  /patient/create:
    post:
      tags:
        - Patient
      summary: Create a new patient folder.
      description: |
        Creates a new folder for a patient record. 
        A name must be provided. 
        If the request is successful, a patientFolderPath will be returned to be stored by the GentleBeam software.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patientName:
                  type: string
                  description: Name for the new study (patient name)
                  nullable: true
              example:
                patientName: "John Doe 10"
      responses:
        '201':
          description: Patient folder created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  patientFolderPath:
                    type: string
                    description: Path for the new patient folder
                required:
                  - patientFolderPath
              example:
                patientFolderPath: "/path/to/John Doe 10"
        '400':
          description: Invalid input
        '409':
          description: Error while creating the folder
  
  /patient/list:
    get:
      tags:
        - Patient
      summary: List patient folders
      description: Lists all existing patients.
      responses:
        '200':
          description: List of patient folders with id and name
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    patientName:
                      type: string
                      example: "John Doe 10"
              example:
                - patientName: "John Doe 10"
                - patientName: "Will Smith 11"
                - patientName: "Martin Solveig 12"
  
  /patient/load:
    get:
      tags:
        - Patient
      summary: Load an existing patient folder
      description: Loads an existing patient folder by providing patient name.
      parameters:
        - name: patientName
          in: query
          required: true
          schema:
            type: string
            example: patient 42
          description: Name of the existing patient
      responses:
        '200':
          description: Patient folder loaded successfully
        '400':
          description: Invalid input
        '404':
          description: Patient folder not found
  
  /patient/delete:
    post:
      tags:
        - Patient
      summary: Delete a patient folder
      description: Deletes a patient folder by providing patient name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patientName:
                  type: string
                  description: Name of the patient (study)
              required:
                - patientName
            example:
              patientName: patient 42
      responses:
        '200':
          description: Patient folder deleted successfully
        '400':
          description: Invalid input
        '404':
          description: Patient folder not found
        '409':
          description: Cannot delete current patient folder
  
  
  # SITE ENDPOINTS
  /site/create:
    post:
      tags:
        - Site
      summary: Create a new site/session
      description: Creates a site/session to store all images for a particular skin site. This facilitates image comparison through the timeline tool.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                siteName:
                  type: string
                  description: Name of the skin site/session
              required:
                - siteName
              example:
                siteName: "Nose left side 12"
      responses:
        '201':
          description: Site/session created successfully
        '400':
          description: Invalid input
        '409':
          description: Site/session with given name already exists

  /site/list:
    get:
      tags:
        - Site
      summary: List all sites/sessions
      description: Lists all existing sites/sessions with their id and name.
      responses:
        '200':
          description: List of sites/sessions with name
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                  siteName:
                    type: string
                    example: Nose left side 12
                example:
                  - siteName: Nose left side 12
                  - siteName: Ear right side 13
                  - siteName: Chin left side 14
                    
  /site/load:
    get:
      tags:
        - Site
      summary: Load a site/session
      description: Loads an existing site/session by its unique siteName.
      parameters:
        - name: siteName
          in: query
          required: true
          schema:
            type: string
            example: "Nose left side 12"
          description: Site/session name to verify access
      responses:
        '200':
          description: Site/session loaded successfully
        '404':
          description: Site/session not found
          
  /site/delete:
    post:
      tags:
        - Site
      summary: Delete a site/session
      description: Deletes a site/session by its unique siteName.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                siteName:
                  type: string
                  description: Site/session name to verify access
              required:
                - siteName
            example:
              siteName: "Nose left side 12"
      responses:
        '200':
          description: Site/session deleted successfully
        '400':
          description: Invalid input
        '404':
          description: Site/session not found
        '500':
          description: Failed to delete current site/session

  # ACQUISITION ENDPOINTS
  /acquisition/list:
    get:
      tags:
        - Acquisition
      summary: List all acquisitions for the current site/session
      description: Lists all existing acquisitions for the currently loaded site/session with their id, name, creation date since epoch in milliseocnds and path to image preview.
      responses:
        '200':
          description: List of acquisitions with id and name
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    acqId:
                      type: integer
                      example: 1
                    acqName:
                      type: string
                      example: "Visit 18/09/2025 - 08:50:25"
                    acqDate:
                      type: long
                      description: Acquisition date in milliseconds since epoch
                      example: 1760691258998
                    acqPreviewPath:
                      type: string
                      nullable: true
                      ewample: "/path/to/preview/image.png"
                example:
                  - acqId: 1
                    acqName: "Visit 18/09/2025 - 08:50:25"
                    acqDate: 1760691258998
                    acqPreviewPath: "/path/to/preview/image_1.png"
                  - acqId: 2
                    acqName: "Visit 20/09/2025 - 10:15:42"
                    acqDate: 1760860542000
                    acqPreviewPath: "/path/to/preview/image_2.png"
                  - acqId: 3
                    acqName: "Visit 22/09/2025 - 11:47:58"
                    acqDate: 1761030478000
                    acqPreviewPath: null
        '403':
            description: No site loaded
          
  /acquisition/load:
    get:
      tags:
        - Acquisition
      summary: Load an acquisition
      description: Loads an existing acquisition by its unique acqId.
      parameters:
        - name: acqId
          in: query
          required: true
          schema:
            type: integer
            example: 1
          description: Acquisition ID to verify access
      responses:
        '200':
          description: Acquisition loaded successfully
        '403':
          description: No site loaded
        '404':
          description: Acquisition not found
      
  /acquisition/delete:
    post:
      tags:
        - Acquisition
      summary: Delete an acquisition
      description: Deletes an acquisition by its unique acqId.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                acqId:
                  type: integer
                  description: Acquisition ID to verify access
              required:
                - acqId
            example:
              acqId: 1
      responses:
        '200':
          description: Acquisition deleted successfully
        '400':
          description: Invalid input
        '404':
          description: Acquisition not found
          
  # MEASUREMENT ENDPOINTS
  /measurements/list:
    get:
      tags:
        - Measurements
      summary: List all measurements for the current site/session
      description: Lists all existing measurements for the currently loaded site/session with their acquisition id and value in mm.
      responses:
        '200':
          description: List of measurements with acqid and value in mm
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    acqId:
                      type: integer
                      example: 1
                    measurementValue:
                      type: float
                      example: 1.56   
                example:
                  - acqId: 1
                    measurementValue: 1.56
                  - acqId: 2
                    measurementValue: 1.23
                  - acqId: 3
                    measurementValue: 0.98
        '404':
            description: No session or acquisition found