syntax = "proto3";

package com.empyreanmed.heracles_robotic_arm.move_commands.v1;

import "com/empyreanmed/heracles_robotic_arm/action_response_tags/v1/action_response_tag.proto";
import "com/empyreanmed/heracles_robotic_arm/axes/v1/axis.proto";
import "com/empyreanmed/heracles_robotic_arm/coordinate_systems/v1/coordinate_system.proto";
import "com/empyreanmed/heracles_robotic_arm/matrices/v1/matrix.proto";
import "com/empyreanmed/heracles_robotic_arm/operating_modes/v1/operating_mode.proto";
import "com/empyreanmed/heracles_robotic_arm/positions/v1/angular_position.proto";
import "com/empyreanmed/heracles_robotic_arm/positions/v1/cartesian_position.proto";
import "com/empyreanmed/heracles_robotic_arm/statuses/v1/status.proto";
import "google/api/field_behavior.proto";

// Basic movement commands service
service MoveCommandsService {
  // Rotate relative to current position
  rpc RotateRelative(RotateRelativeRequest) returns (RotateRelativeResponse) {}

  // Rotate relative to current position via action
  rpc RotateRelativeAction(RotateRelativeActionRequest) returns (stream RotateRelativeActionResponse) {}

  // Translate relative to current position
  rpc TranslateRelative(TranslateRelativeRequest) returns (TranslateRelativeResponse) {}

  // Translate relative to current position via action
  rpc TranslateRelativeAction(TranslateRelativeActionRequest) returns (stream TranslateRelativeActionResponse) {}

  // Move the robot to stored position defined by J1-J6 angular values/position
  rpc MoveCustomAction(MoveCustomActionRequest) returns (stream MoveCustomActionResponse) {}

  // Move the robot to word position defined by pose (cartesian [X,Y,Z] and angular [Rx, Ry, Rz] coordinates)
  rpc MoveToPositionAction(MoveToPositionActionRequest) returns (stream MoveToPositionActionResponse) {}

  // Move by matrix relative to current position
  rpc MoveByMatrixAction(MoveByMatrixActionRequest) returns (stream MoveByMatrixActionResponse) {}

  // Stop any ongoing asynchronous motion
  rpc StopMotion(StopMotionRequest) returns (StopMotionResponse) {}

  // Command to check communications
  rpc PingAction(PingActionRequest) returns (stream PingActionResponse) {}

  // Set operating mode
  rpc SetOperatingModeAction(SetOperatingModeActionRequest) returns (stream SetOperatingModeActionResponse) {}

  // Get KeepAlive stream
  rpc GetKeepAlive(GetKeepAliveRequest) returns (stream GetKeepAliveResponse) {}

  // Check if client operates on an emulated hardware
  rpc IsFakeHardware(IsFakeHardwareRequest) returns (IsFakeHardwareResponse) {}

  // Get the position of the End Effector in world coordinates [X,Y,Z, Rx, Ry, Rz]
  rpc GetPosition(GetPositionRequest) returns (GetPositionResponse) {}

  // Get the angular position of joints J1-J6
  rpc GetJointsPosition(GetJointsPositionRequest) returns (GetJointsPositionResponse) {}

  // Converts translate relative/absolute to word position defined by pose (cartesian [X,Y,Z] and angular [Rx, Ry, Rz] coordinates), no robot motion
  rpc ConvertTranslateRelativeToPosition(ConvertTranslateRelativeToPositionRequest) returns (ConvertTranslateRelativeToPositionResponse) {}

  // Converts rotate relative/absolute to word position defined by pose (cartesian [X,Y,Z] and angular [Rx, Ry, Rz] coordinates), no robot motion
  rpc ConvertRotateRelativeToPosition(ConvertRotateRelativeToPositionRequest) returns (ConvertRotateRelativeToPositionResponse) {}
}

// Request message for TranslateRelativeAction
message TranslateRelativeActionRequest {
  // Axis
  optional com.empyreanmed.heracles_robotic_arm.axes.v1.Axis axis = 1 [(google.api.field_behavior) = REQUIRED];
  // Distance, mm
  optional float mm = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message for TranslateRelativeAction
message TranslateRelativeActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback cartesian position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition feedback_position_mm = 3 [(google.api.field_behavior) = REQUIRED];
  // Feedback angular position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition feedback_position_deg = 4 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 5 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 6 [(google.api.field_behavior) = REQUIRED];
}

// Request message for RotateRelativeAction
message RotateRelativeActionRequest {
  // Axis
  optional com.empyreanmed.heracles_robotic_arm.axes.v1.Axis axis = 1 [(google.api.field_behavior) = REQUIRED];
  // Angle, deg
  optional float deg = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message for RotateRelativeAction
message RotateRelativeActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback cartesian position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition feedback_position_mm = 3 [(google.api.field_behavior) = REQUIRED];
  // Feedback angular position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition feedback_position_deg = 4 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 5 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 6 [(google.api.field_behavior) = REQUIRED];
}

// Request message for RotateRelative
message RotateRelativeRequest {
  // Axis
  optional com.empyreanmed.heracles_robotic_arm.axes.v1.Axis axis = 1 [(google.api.field_behavior) = REQUIRED];
  // Angle, deg
  optional float deg = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message for RotateRelative
message RotateRelativeResponse {
  // Accepted
  optional bool accepted = 1 [(google.api.field_behavior) = REQUIRED];
}

// Request message for TranslateRelative
message TranslateRelativeRequest {
  // Axis
  optional com.empyreanmed.heracles_robotic_arm.axes.v1.Axis axis = 1 [(google.api.field_behavior) = REQUIRED];
  // Distance, mm
  optional float mm = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message for TranslateRelative
message TranslateRelativeResponse {
  // Accepted
  optional bool accepted = 1 [(google.api.field_behavior) = REQUIRED];
}

// Define a message with an array of 6 doubles - J1 - J6
message MoveCustomActionRequest {
  // This should contain exactly 6 elements
  repeated double values_rad = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message for MoveCustomAction
message MoveCustomActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback joints positions
  repeated double feedback_joints_positions_rad = 3 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 4 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 5 [(google.api.field_behavior) = REQUIRED];
}

// Request message for MoveToPositionAction
message MoveToPositionActionRequest {
  // Cartesian word position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition world_position_mm = 1 [(google.api.field_behavior) = REQUIRED];
  // Angular word position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition world_position_deg = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message for MoveToPositionAction
message MoveToPositionActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback cartesian position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition feedback_position_mm = 3 [(google.api.field_behavior) = REQUIRED];
  // Feedback angular position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition feedback_position_deg = 4 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 5 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 6 [(google.api.field_behavior) = REQUIRED];
}

// Request message for MoveByMatrixAction
message MoveByMatrixActionRequest {
  // Matrix
  optional com.empyreanmed.heracles_robotic_arm.matrices.v1.Matrix4x4 matrix4x4 = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message for MoveByMatrixAction
message MoveByMatrixActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback joints positions
  repeated double feedback_joints_positions_rad = 3 [(google.api.field_behavior) = REQUIRED];
  // Feedback cartesian position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition feedback_position_mm = 4 [(google.api.field_behavior) = REQUIRED];
  // Feedback angular position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition feedback_position_deg = 5 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 6 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 7 [(google.api.field_behavior) = REQUIRED];
}

// Request message for StopMotion
message StopMotionRequest {}

// Response message for StopMotion
message StopMotionResponse {
  // Accepted
  optional bool accepted = 1 [(google.api.field_behavior) = REQUIRED];
}

// Request message for PingAction
message PingActionRequest {
  // Pongs amount
  optional int32 pongs_amount = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message for PingAction
message PingActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback pong id
  optional int32 feedback_pong_id = 3 [(google.api.field_behavior) = REQUIRED];
  // Result pongs total
  optional int32 result_pongs_total = 4 [(google.api.field_behavior) = REQUIRED];
}

// Request message for SetOperatingModeAction
message SetOperatingModeActionRequest {
  // Operating mode
  optional com.empyreanmed.heracles_robotic_arm.operating_modes.v1.OperatingMode operating_mode = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message for SetOperatingModeAction
message SetOperatingModeActionResponse {
  // Tag
  optional com.empyreanmed.heracles_robotic_arm.action_response_tags.v1.ActionResponseTag tag = 1 [(google.api.field_behavior) = REQUIRED];
  // Goal accepted
  optional bool goal_accepted = 2 [(google.api.field_behavior) = REQUIRED];
  // Feedback is empty
  // Result success
  optional bool result_success = 3 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 4 [(google.api.field_behavior) = REQUIRED];
  // Result operating mode
  optional com.empyreanmed.heracles_robotic_arm.operating_modes.v1.OperatingMode result_operating_mode = 5 [(google.api.field_behavior) = REQUIRED];
}

// Request message for GetKeepAlive
message GetKeepAliveRequest {
  // Empty
}

// Response message for GetKeepAlive
message GetKeepAliveResponse {
  // Status
  optional com.empyreanmed.heracles_robotic_arm.statuses.v1.Status status = 1 [(google.api.field_behavior) = REQUIRED];
}

// Request message for IsFakeHardware
message IsFakeHardwareRequest {
  // Empty
}

// Response message for IsFakeHardware
message IsFakeHardwareResponse {
  // Status
  optional bool is_fake_hardware = 1 [(google.api.field_behavior) = REQUIRED];
}

// Request message for GetPosition
message GetPositionRequest {
  // Empty
}

// Response message for GetPosition
message GetPositionResponse {
  // Cartesian position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition feedback_position_mm = 1 [(google.api.field_behavior) = REQUIRED];
  // Angular position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition feedback_position_deg = 2 [(google.api.field_behavior) = REQUIRED];
}

// Request message for GetJointsPosition
message GetJointsPositionRequest {
  // Empty
}

// Response message for GetJointsPosition
message GetJointsPositionResponse {
  // Joints positions
  repeated double feedback_joints_positions_rad = 3 [(google.api.field_behavior) = REQUIRED];
}

// Request message for ConvertTranslateRelativeToPosition
message ConvertTranslateRelativeToPositionRequest {
  // Axis
  optional com.empyreanmed.heracles_robotic_arm.axes.v1.Axis axis = 1 [(google.api.field_behavior) = REQUIRED];
  // Distance, mm
  optional float distance_mm = 2 [(google.api.field_behavior) = REQUIRED];
  // Coordinate system
  optional com.empyreanmed.heracles_robotic_arm.coordinate_systems.v1.CoordinateSystem coordinate_system = 3 [(google.api.field_behavior) = REQUIRED];
}

// Response message for ConvertTranslateRelativeToPosition
message ConvertTranslateRelativeToPositionResponse {
  // Cartesian word position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition world_position_mm = 1 [(google.api.field_behavior) = REQUIRED];
  // Angular word position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition world_position_deg = 2 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 3 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 4 [(google.api.field_behavior) = REQUIRED];
}

// Request message for ConvertRotateRelativeToPosition
message ConvertRotateRelativeToPositionRequest {
  // Axis
  optional com.empyreanmed.heracles_robotic_arm.axes.v1.Axis axis = 1 [(google.api.field_behavior) = REQUIRED];
  // Angle, deg
  optional float angle_deg = 2 [(google.api.field_behavior) = REQUIRED];
  // Coordinate system
  optional com.empyreanmed.heracles_robotic_arm.coordinate_systems.v1.CoordinateSystem coordinate_system = 3 [(google.api.field_behavior) = REQUIRED];
}

// Response message for ConvertRotateRelativeToPosition
message ConvertRotateRelativeToPositionResponse {
  // Cartesian word position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.CartesianPosition world_position_mm = 1 [(google.api.field_behavior) = REQUIRED];
  // Angular word position
  optional com.empyreanmed.heracles_robotic_arm.positions.v1.AngularPosition world_position_deg = 2 [(google.api.field_behavior) = REQUIRED];
  // Result success
  optional bool result_success = 3 [(google.api.field_behavior) = REQUIRED];
  // Result details
  optional string result_details = 4 [(google.api.field_behavior) = REQUIRED];
}
