
namespace Xcc.Core.Enums
{
    public enum GCBTelemetryResponseField : int
    {
        SystemState = 0,
        SystemRuntime,
        SystemFaultFlags,        
        InterlockFlags,
        RingLedState,
        BaseLedState,
        Collimator1,
        Collimator2,
        Buttons,
        CurrentPoint,
        TotalPoints,
        InternalTimerState,
        InternalTimerValue,
        Timer1State,
        Timer1Value,
        Timer2State,
        Timer2Value,
        HvpsRuntime,
        HvpsIO,
        HvpsStatusFlags,
        kVFeedback,
        mAFeedback,
        FilamentSetpoint,
        FilamentFeedback,
        GridSetpoint,
        GridFeedback,
        XCoilCurrent,
        YCoilCurrent,
        FocusCoilCurrent,
        IonPumpFeedback,
        WaterPressure,
        WaterFlow,
        WaterTemp,
        HeatsinkTemp,
        PeltierTemp,
        CabinetTemp,
        Mag1X,
        Mag1Y,
        Mag1Z,
        Mag2X,
        Mag2Y,
        Mag2Z,
        Applicator,
        kVSetpoint,
        emissionCurrentLimit,
        hvpsPowerSetpoint,
        PayloadFields, // number of fields in total
    }
}
