<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <BuildNumber>0</BuildNumber>
    <InformationalVersion>$(AssemblyVersion) SP $(BuildNumber) </InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.30.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Xcc.Infra\Xcc.Infra.csproj" />
    <ProjectReference Include="..\Heracles.Application\Heracles.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>
</Project>
