<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <AssemblyVersion>1.1.21</AssemblyVersion>
    <BuildNumber>0</BuildNumber>
    <InformationalVersion>$(AssemblyVersion) SP $(BuildNumber) </InformationalVersion>
    <ApplicationIcon>Heracles.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <Compile Remove="Reoruces\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <EmbeddedResource Remove="Reoruces\**" />
    <None Remove="Helpers\**" />
    <None Remove="Reoruces\**" />
    <Page Remove="Helpers\**" />
    <Page Remove="Reoruces\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Heracles.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Xcc.Shared\Xcc.Shared.csproj" />
    <ProjectReference Include="..\Heracles.Application\Heracles.Application.csproj" />
    <ProjectReference Include="..\Heracles.Indoor.SqliteGrpcServer\Heracles.Indoor.SqliteGrpcServer.csproj" />
    <ProjectReference Include="..\Heracles.Ucsi\Heracles.Ucsi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\FieldDetailsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Physics\OutputFactorsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Physics\HeaterCurrentView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Physics\MagnetometerView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Physics\TargetPointsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Physics\ConfigurationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ClinicalDataTabsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ImagesView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PrescriptionSummary1View.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PrescriptionSummaryView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\QualityCheck\QualityCheckView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Settings\SettingsTabsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Settings\TargetManagementView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Patients\Patient\Treatments\TreatmentsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\CameraView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ImagingView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\SimulationSummaryView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\SitesView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PlanView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MainTabsView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\PrescriptionView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\SimulationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ClinicalDataView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\EmptyView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.local-dual.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
