syntax = "proto3";

package com.empyreanmed.heracles.prescriptions.v1;

import "com/empyreanmed/heracles/prescriptions/v1/prescription.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/field_mask.proto";

// Performs operations on prescriptions.
service PrescriptionService {
  // Lists prescriptions for a given simulation.
  rpc ListPrescriptions(ListPrescriptionsRequest) returns (ListPrescriptionsResponse);

  // Returns a single prescription.
  rpc GetPrescription(GetPrescriptionRequest) returns (GetPrescriptionResponse);

  // Creates a new prescription for a simulation.
  rpc CreatePrescription(CreatePrescriptionRequest) returns (CreatePrescriptionResponse);

  // Updates an existing prescription.
  rpc UpdatePrescription(UpdatePrescriptionRequest) returns (UpdatePrescriptionResponse);

  // Deletes a prescription.
  rpc DeletePrescription(DeletePrescriptionRequest) returns (DeletePrescriptionResponse);
}

// Request message for listing prescriptions.
message ListPrescriptionsRequest {
  // The ID of the simulation for which to list prescriptions.
  optional int64 simulation_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the listed prescriptions.
message ListPrescriptionsResponse {
  // The prescriptions matching the list request. The order is unspecified.
  repeated Prescription prescriptions = 1 [(google.api.field_behavior) = UNORDERED_LIST];
}

// Request message for fetching a single prescription.
message GetPrescriptionRequest {
  // The ID of the prescription to fetch.
  optional int64 id = 1 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the fetched prescription.
message GetPrescriptionResponse {
  // The prescription with the provided ID.
  Prescription prescription = 1;
}

// Request message for creating a new prescription.
message CreatePrescriptionRequest {
  // Details of the prescription to create.
  optional Prescription prescription = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the created prescription.
message CreatePrescriptionResponse {
  // The prescription that was created.
  optional Prescription prescription = 1;
}

// Request message for updating an existing prescription.
message UpdatePrescriptionRequest {
  // The prescription to update.
  optional Prescription prescription = 1 [(google.api.field_behavior) = REQUIRED];

  // A FieldMask specifying which fields of the prescription to update.
  optional google.protobuf.FieldMask update_mask = 2 [(google.api.field_behavior) = REQUIRED];
}

// Response message with the updated prescription.
message UpdatePrescriptionResponse {
  // The updated prescription.
  Prescription prescription = 1;
}

// Request message for deleting a prescription.
message DeletePrescriptionRequest {
  // The ID of the prescription to delete.
  optional int64 prescription_id = 1 [(google.api.field_behavior) = REQUIRED];
}

// An empty response message for `DeletePrescription`.
message DeletePrescriptionResponse {}
