<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <UseWindowsForms>True</UseWindowsForms>
    <Company>Empyrean Medical</Company>
    <Product>KukaRdpHost</Product>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AxMSTSCLib">
      <HintPath>AxMSTSCLib.dll</HintPath>
    </Reference>
    <Reference Include="MSTSCLib">
      <HintPath>MSTSCLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
