using Microsoft.Extensions.Configuration;

namespace Empyrean.Common.Infra.Settings
{
    public class SettingsReader(IConfiguration configuration) : ISettingsReader
    {
        public int GetInt(string key) 
            => GetValue<int>(key);

        public double GetDouble(string key)
            => GetValue<double>(key);

        public string GetString(string key)
            => GetValue<string>(key);

        public T GetValue<T>(string key)
        {
            try
            {
                return configuration.GetValue<T>(key) ?? throw new SettingsConfigurationException($"{key} key not specified in provided configuration.");
            }
            catch (Exception ex)
            {
                //no need to output string value to the exception, since inner exceptions, generated by IConfiguration implementation already contains the value
                throw new SettingsConfigurationException($"Failed to parse {key} from provided configuration.", ex);
            }
        }

        public int GetOptionalInt(string key, int defaultValue) 
            => configuration.GetValue(key, defaultValue);

        public long GetOptionalLong(string key, long defaultValue)
            => configuration.GetValue(key, defaultValue);

        public bool GetOptionalBool(string key, bool defaultValue) 
            => configuration.GetValue(key, defaultValue);

        public double GetOptionalDouble(string key, double defaultValue)
            => configuration.GetValue(key, defaultValue);

        public float GetOptionalFloat(string key, float defaultValue)
            => configuration.GetValue(key, defaultValue);

        public string GetOptionalString(string key, string defaultValue)
            => configuration.GetValue<string>(key) ?? defaultValue;

        public string? GetOptionalString(string key)
            => configuration.GetValue<string>(key);

        public T? GetOptionalValue<T>(string key)
        {
            try
            {
                return configuration.GetValue<T>(key);
            }
            catch (Exception)
            {
                return default;
            }
        }
    }
}
